In [1]:
#<table class="wikitable sortable jquery-tablesorter" style="width:100%; text-align:center;">
import pandas as pd
import numpy as np
import regex

In [2]:

dfs=pd.read_html("https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population")
# df = pd.read_csv("cities of india.csv")
# df.head()

In [3]:
len(dfs)

3

In [4]:
dfs1=dfs[0]
dfs1

,Rank,City,Population(2011)[3],Population(2001),State or union territory
0,1,Mumbai,12442373,11978450,Maharashtra
1,2,Delhi,11007835,9879172,Delhi
2,3,Bangalore,8425970,4301326,Karnataka
3,4,Hyderabad,6809970,3637483,Telangana
4,5,Ahmedabad,5570585,3520085,Gujarat
...,...,...,...,...,...
319,320,Tezpur,102505,83028,Assam
320,321,Jehanabad[35],102456,81503,Bihar
321,322,Aurangabad[36],101520,79393,Bihar
322,323,Gangtok,100286,29354,Sikkim
323,324,Vasco Da Gama,100000,―,Goa

In [5]:
pd.set_option('display.max_rows', None)

In [6]:
dfs1.to_csv("cities of india.csv")

In [7]:
type(dfs1)

pandas.core.frame.DataFrame

In [8]:
type(dfs1)

pandas.core.frame.DataFrame

In [9]:
dfs1.rename(columns = {'City':'Cities', 'Population(2011)[3]':'Population(2011)','State or union territory':"State or Union Territory"}, inplace = True)

dfs1

,Rank,Cities,Population(2011),Population(2001),State or Union Territory
0,1,Mumbai,12442373,11978450,Maharashtra
1,2,Delhi,11007835,9879172,Delhi
2,3,Bangalore,8425970,4301326,Karnataka
3,4,Hyderabad,6809970,3637483,Telangana
4,5,Ahmedabad,5570585,3520085,Gujarat
5,6,Chennai,4681087,4343645,Tamil Nadu
6,7,Kolkata,4486679,4572876,West Bengal
7,8,Surat,4467797,2433835,Gujarat
8,9,Pune,3115431,2538473,Maharashtra
9,10,Jaipur,3046163,2322575,Rajasthan
10,11,Lucknow,2815601,2185927,Uttar Pradesh
11,12,Kanpur,2767031,2551337,Uttar Pradesh
12,13,Nagpur,2405665,2052066,Maharashtra
13,14,Indore,1960631,1474968,Madhya Pradesh
14,15,Thane,1818872,1262551,Maharashtra
15,16,Bhopal,1795648,1437354,Madhya Pradesh
16,17,Visakhapatnam[4],1730320,1345938,Andhra Pradesh
17,18,Pimpri-Chinchwad,1727692,1012472,Maharashtra
18,19,Patna,1684222,1366444,Bihar
19,20,Vadodara,1670806,1306227,Gujarat
20,21,Ghaziabad,1648643,968256,Uttar Pradesh
21,22,Ludhiana,1618879,1398467,Punjab
22,23,Agra,1585704,1275134,Uttar Pradesh
23,24,Nashik,1486053,1077236,Maharashtra
24,25,Faridabad,1414050,1055938,Haryana
25,26,Meerut,1305429,1039405,Uttar Pradesh
26,27,Rajkot,1286678,967476,Gujarat
27,28,Kalyan-Dombivli,1247327,1193512,Maharashtra
28,29,Vasai-Virar,1222390,693350,Maharashtra
29,30,Varanasi,1201815,1091918,Uttar Pradesh
30,31,Srinagar,1180570,898440,Jammu and Kashmir
31,32,Aurangabad,1175116,873311,Maharashtra
32,33,Dhanbad,1162472,1065327,Jharkhand
33,34,Amritsar,1132383,966862,Punjab
34,35,Navi Mumbai,1120547,704002,Maharashtra
35,36,Allahabad,1112544,975393,Uttar Pradesh
36,37,Howrah,1077075,1007532,West Bengal
37,38,Ranchi,1073427,847093,Jharkhand
38,39,Gwalior,1069276,827026,Madhya Pradesh
39,40,Jabalpur,1055525,932484,Madhya Pradesh
40,41,Coimbatore,"1,050,721 [5]",930882,Tamil Nadu
41,42,Vijayawada,1034358,851282,Andhra Pradesh
42,43,Jodhpur,1033918,851051,Rajasthan
43,44,Madurai,1017865,928869,Tamil Nadu
44,45,Raipur,1010087,605747,Chhattisgarh
45,46,Kota[6],1001694,694316,Rajasthan
46,47,Chandigarh,960787,808515,Chandigarh
47,48,Guwahati,957352,809895,Assam
48,49,Solapur,951558,872478,Maharashtra
49,50,Hubli–Dharwad,943788,786195,Karnataka
50,51,Mysore[7][8][9],920550,762408,Karnataka
51,52,Tiruchirappalli[10],916674,752066,Tamil Nadu
52,53,Bareilly,898167,718395,Uttar Pradesh
53,54,Aligarh,889810,672315,Uttar Pradesh
54,55,Tiruppur,877778,344543,Tamil Nadu
55,56,Gurgaon,876824,173542,Haryana
56,57,Moradabad,872575,669087,Uttar Pradesh
57,58,Jalandhar,862196,706043,Punjab
58,59,Bhubaneswar,837737,648032,Odisha
59,60,Salem,831038,696760,Tamil Nadu
60,61,Warangal[11][12],830281,530636,Telangana
61,62,Mira-Bhayandar,814655,520388,Maharashtra
62,63,Jalgaon,798514,462280,Maharashtra
63,64,Guntur[13],670073,514461,Andhra Pradesh
64,65,Thiruvananthapuram,752490,368618,Kerala
65,66,Bhiwandi,711329,598741,Maharashtra
66,67,Saharanpur,703345,455754,Uttar Pradesh
67,68,Gorakhpur,671048,622701,Uttar Pradesh
68,69,Bikaner,647804,529690,Rajasthan
69,70,Amravati,646801,549510,Maharashtra
70,71,Noida,642381,305058,Uttar Pradesh
71,72,Jamshedpur,631364,573096,Jharkhand
72,73,Bhilai,625697,556366,Chhattisgarh
73,74,Cuttack,606007,534654,Odisha
74,75,Firozabad,603797,279102,Uttar Pradesh
75,76,Kochi,601574,596473,Kerala
76,77,Nellore[14][15],558548,378428,Andhra Pradesh
77,78,Bhavnagar,593768,511085,Gujarat
78,79,Dehradun,578420,426674,Uttarakhand
79,80,Durgapur,566937,493405,West Bengal
80,81,Asansol,564491,475439,West Bengal
81,82,Rourkela,552734,426354,Odisha
82,83,Nanded,550564,430733,Maharashtra
83,84,Kolhapur,549283,493167,Maharashtra
84,85,Ajmer,542580,485575,Rajasthan
85,86,Akola,537149,400520,Maharashtra
86,87,Gulbarga,532031,422569,Karnataka
87,88,Jamnagar,529308,443518,Gujarat
88,89,Ujjain,515215,430427,Madhya Pradesh
89,90,Loni,512296,120945,Uttar Pradesh
90,91,Siliguri,509709,472374,West Bengal
91,92,Jhansi,507293,383644,Uttar Pradesh
92,93,Ulhasnagar,506937,473731,Maharashtra
93,94,Jammu[16],503690,369959,Jammu and Kashmir
94,95,Sangli-Miraj & Kupwad,502697,436781,Maharashtra
95,96,Mangalore,499486,399565,Karnataka
96,97,Erode[17],498129,173600,Tamil Nadu
97,98,Belgaum,488292,399653,Karnataka
98,99,Kurnool[18],484327,345987,Andhra Pradesh
99,100,Ambattur,478134,310967,Tamil Nadu
100,101,Rajahmundry[19][20],476873,315251,Andhra Pradesh
101,102,Tirunelveli,473637,411831,Tamil Nadu
102,103,Malegaon,471006,409403,Maharashtra
103,104,Gaya,463454,385432,Bihar
104,105,Udaipur,451735,389438,Rajasthan
105,106,Karur,444506,158955,Tamil Nadu
106,107,Kakinada,443028,325985,Andhra Pradesh
107,108,Davanagere,435128,364523,Karnataka
108,109,Kozhikode,432097,436556,Kerala
109,110,Maheshtala,429423,385266,West Bengal
110,111,Rajpur Sonarpur,423806,336707,West Bengal
111,112,Bokaro,413934,393805,Jharkhand
112,113,South Dum Dum,410524,392444,West Bengal
113,114,Bellary,409644,316766,Karnataka
114,115,Patiala,405164,303151,Punjab
115,116,Gopalpur,404991,271811,West Bengal
116,117,Agartala,399688,271811,Tripura
117,118,Bhagalpur,398138,340767,Bihar
118,119,Muzaffarnagar,392451,316729,Uttar Pradesh
119,120,Bhatpara,390467,442385,West Bengal
120,121,Panihati,383522,348438,West Bengal
121,122,Latur,382754,299985,Maharashtra
122,123,Dhule,376093,341755,Maharashtra
123,124,Rohtak,373133,286807,Haryana
124,125,Sagar,370296,232133,Madhya Pradesh
125,126,Korba,363210,315690,Chhattisgarh
126,127,Bhilwara,360009,280128,Rajasthan
127,128,Berhampur,355823,307792,Odisha
128,129,Muzaffarpur,351838,305525,Bihar
129,130,Ahmednagar,350905,307615,Maharashtra
130,131,Mathura,349336,302770,Uttar Pradesh
131,132,Kollam,349033,361560,Kerala
132,133,Avadi,344701,229403,Tamil Nadu
133,134,Kadapa[21],344893,125725,Andhra Pradesh
134,135,Anantapuram[21],340613,255134,Andhra Pradesh
135,136,Kamarhati,336579,314507,West Bengal
136,137,Bilaspur,335761,296662,Chhattisgarh
137,138,Sambalpur,330106,274917,Odisha
138,139,Shahjahanpur,327975,296662,Uttar Pradesh
139,140,Satara,326789,228175,Maharashtra
140,141,Bijapur,326360,228175,Karnataka
141,142,Rampur,325248,281494,Uttar Pradesh
142,143,Shimoga,322428,274352,Karnataka
143,144,Chandrapur,321036,289450,Maharashtra
144,145,Junagadh,320250,168686,Gujarat
145,146,Thrissur,315596,317526,Kerala
146,147,Alwar,315310,260593,Rajasthan
147,148,Bardhaman,314638,285602,West Bengal
148,149,Kulti,313977,289903,West Bengal
149,150,Nizamabad,310467,288722,Telangana
150,151,Parbhani,307191,259329,Maharashtra
151,152,Tumkur,305821,248929,Karnataka
152,153,Khammam,305000,218689,Telangana
153,154,Uzhavarkarai,300028,217707,Puducherry
154,155,Bihar Sharif,296889,232071,Bihar
155,156,Panipat,294150,261740,Haryana
156,157,Darbhanga,294116,267348,Bihar
157,158,Bally,291972,260906,West Bengal
158,159,Aizawl,291822,228280,Mizoram
159,160,Dewas,289438,231672,Madhya Pradesh
160,161,Ichalkaranji,287570,257610,Maharashtra
161,162,Karnal,286974,210476,Haryana
162,163,Bathinda,285813,217256,Punjab
163,164,Jalna,285349,235795,Maharashtra
164,165,Eluru[22],283648,190347,Andhra Pradesh
165,166,Barasat,283443,231515,West Bengal
166,167,Kirari Suleman Nagar,282598,153874,Delhi
167,168,Purnia[23],280547,171687,Bihar
168,169,Satna,280248,225464,Madhya Pradesh
169,170,Mau,279060,212657,Uttar Pradesh
170,171,Sonipat,277053,214974,Haryana
171,172,Farrukhabad,275750,228333,Uttar Pradesh
172,173,Durg,268679,232517,Chhattisgarh
173,174,Imphal,264986,221492,Manipur
174,175,Ratlam,264810,222202,Madhya Pradesh
175,176,Hapur,262801,211983,Uttar Pradesh
176,177,Arrah,261099,203380,Bihar
177,178,Anantapur,261004,218808,Andhra Pradesh
178,179,Karimnagar,260899,205653,Telangana
179,180,Etawah,256838,210453,Uttar Pradesh
180,181,Ambarnath,254003,203795,Maharashtra
181,182,North Dum Dum,253625,220042,West Bengal
182,183,Bharatpur,252109,204587,Rajasthan
183,184,Begusarai,251136,93378,Bihar
184,185,New Delhi,249998,302147,Delhi
185,186,Gandhidham,248705,166388,Gujarat
186,187,Baranagar,248466,250768,West Bengal
187,188,Tiruvottiyur,248059,212281,Tamil Nadu
188,189,Pondicherry,241773,220749,Puducherry
189,190,Sikar,237579,184904,Rajasthan
190,191,Thoothukudi,237374,216058,Tamil Nadu
191,192,Rewa,235422,183274,Madhya Pradesh
192,193,Mirzapur,233691,205053,Uttar Pradesh
193,194,Raichur,232456,207421,Karnataka
194,195,Pali,229956,187641,Rajasthan
195,196,Ramagundam[24],229644,236600,Telangana
196,197,Silchar,229136,184105,Assam
197,198,Haridwar,228832,175010,Uttarakhand
198,199,Vijayanagaram,228025,174324,Andhra Pradesh
199,200,Tenali,225982,184937,Andhra Pradesh
200,201,Nagercoil,224849,208179,Tamil Nadu
201,202,Sri Ganganagar,224773,210713,Rajasthan
202,203,Karawal Nagar,224666,148549,Delhi
203,204,Mango,223805,166125,Jharkhand
204,205,Thanjavur,222943,215314,Tamil Nadu
205,206,Bulandshahr,222519,176425,Uttar Pradesh
206,207,Uluberia,222240,202135,West Bengal
207,208,Katni,221883,187029,Madhya Pradesh
208,209,Sambhal,220813,182478,Uttar Pradesh
209,210,Singrauli,220257,185190,Madhya Pradesh
210,211,Nadiad,218095,192913,Gujarat
211,212,Secunderabad,217910,206102,Telangana
212,213,Naihati,217900,215303,West Bengal
213,214,Yamunanagar,216677,189696,Haryana
214,215,Bidhannagar,215514,164221,West Bengal
215,216,Pallavaram,215417,144623,Tamil Nadu
216,217,Bidar,214373,172877,Karnataka
217,218,Munger,213303,188050,Bihar
218,219,Panchkula,211355,140925,Haryana
219,220,Burhanpur,210886,193725,Madhya Pradesh
220,221,Kharagpur,207604,188761,West Bengal
221,222,Dindigul,207327,196955,Tamil Nadu
222,223,Gandhinagar,206167,195985,Gujarat
223,224,Hospet,206167,164240,Karnataka
224,225,Nangloi Jat,205596,150948,Delhi
225,226,Malda,205521,161456,West Bengal
226,227,Ongole,204746,150471,Andhra Pradesh
227,228,Deoghar,203123,112525,Jharkhand
228,229,Chhapra,202352,79190,Bihar
229,230,Puri,201026,152682,Odisha
230,231,Haldia,200827,170673,West Bengal
231,232,Khandwa,200738,172242,Madhya Pradesh
232,233,Nandyal,200516,152676,Andhra Pradesh
233,234,Morena,200482,150959,Madhya Pradesh
234,235,Amroha,198471,165129,Uttar Pradesh
235,236,Anand,198282,130685,Gujarat
236,237,Bhind,197585,153752,Madhya Pradesh
237,238,Bhalswa Jahangir Pur,197148,152339,Delhi
238,239,Madhyamgram,196127,155451,West Bengal
239,240,Bhiwani,196057,169531,Haryana
240,241,Berhampore,195223,160143,West Bengal
241,242,Ambala,195153,139279,Haryana
242,243,Morbi,194947,145719,Gujarat
243,244,Fatehpur,193193,151757,Uttar Pradesh
244,245,Raebareli,191316,169333,Uttar Pradesh
245,246,"Khora, Ghaziabad",190400,―,Uttar Pradesh
246,247,Chittoor[25],189332,152654,Andhra Pradesh
247,248,Bhusawal,187421,172372,Maharashtra
248,249,Orai,187137,139318,Uttar Pradesh
249,250,Bahraich,186223,168323,Uttar Pradesh
250,251,Phusro,186139,83463,Jharkhand
251,252,Vellore,185803,177230,Tamil Nadu
252,253,Mehsana,184991,141453,Gujarat
253,254,Raiganj,183612,165212,West Bengal
254,255,Sirsa,182534,160735,Haryana
255,256,Danapur,182429,131176,Bihar
256,257,Serampore,181842,197857,West Bengal
257,258,Sultan Pur Majra,181554,164426,Delhi
258,259,Guna,180935,137175,Madhya Pradesh
259,260,Jaunpur,180362,160055,Uttar Pradesh
260,261,Panvel,180020,104058,Maharashtra
261,262,Shivpuri,179977,146892,Madhya Pradesh
262,263,Surendranagar Dudhrej,177851,156161,Gujarat
263,264,Unnao,177658,144662,Uttar Pradesh
264,265,Chinsurah,177259,170201,West Bengal
265,266,Alappuzha,174164,177029,Kerala
266,267,Kottayam,172878,129894,Kerala
267,268,Machilipatnam,169892,179353,Andhra Pradesh
268,269,Shimla,169578,142555,Himachal Pradesh
269,270,Midnapore,169127,149768,West Bengal
270,271,Adoni,166537,―,Andhra Pradesh
271,272,Udupi,165401,―,Karnataka
272,273,Katihar,164937,115169,Bihar
273,274,Proddatur,163600,86896,Andhra Pradesh
274,275,Budaun,159221,148029,Uttar Pradesh
275,276,Mahbubnagar,158000,–,Telangana
276,277,Saharsa[26],155175,125167,Bihar
277,278,Dibrugarh,154296,137661,Assam
278,279,Jorhat,153889,112026,Assam
279,280,Hazaribagh,153599,127243,Jharkhand
280,281,Hindupur,151835,―,Andhra Pradesh
281,282,Raigarh,150019,115908,Chhattisgarh
282,283,Nagaon,148496,123265,Assam
283,284,Hajipur[27],147688,119412,Bihar
284,285,Sasaram[28],147396,131172,Bihar
285,286,Giridih,143529,―,Jharkhand
286,287,Bhimavaram,142280,―,Andhra Pradesh
287,288,Port Blair,140572,—,Andaman and Nicobar Islands UT
288,289,Kumbakonam,140056,144021,Tamil Nadu
289,290,Bongaigaon,139650,101213,Assam
290,291,Dehri[28],137068,119057,Bihar
291,292,Madanapalle,135669,―,Andhra Pradesh
292,293,Siwan[29],134458,109919,Bihar
293,294,Bettiah[30],132896,116670,Bihar
294,295,Ramgarh,132441,73455,Jharkhand
295,296,Tinsukia,126389,101957,Assam
296,297,Guntakal,126270,―,Andhra Pradesh
297,298,Srikakulam,125939,―,Andhra Pradesh
298,299,Motihari[31],125183,100683,Bihar
299,300,Dharmavaram,121874,―,Andhra Pradesh
300,301,Medininagar,120325,―,Jharkhand
301,302,Gudivada,118167,―,Andhra Pradesh
302,303,Phagwara,117966,―,Punjab
303,304,Pudukkottai,117745,―,Tamil Nadu
304,305,Hosur,116821,102000,Tamil Nadu
305,306,Narasaraopet,116250,―,Andhra Pradesh
306,307,Suryapet,115250,94585,Telangana
307,308,Miryalaguda,109891,91395,Telangana
308,309,Anantnag,108505,―,Jammu and Kashmir
309,310,Tadipatri,108171,―,Andhra Pradesh
310,311,Karaikudi,106714,86596,Tamil Nadu
311,312,Kishanganj[32],105782,85590,Bihar
312,313,Gangavathi,105529,85459,Karnataka
313,314,Jamalpur[33],105221,96983,Bihar
314,315,Ballia,104271,―,Uttar Pradesh
315,316,Kavali,104000,―,Andhra Pradesh
316,317,Tadepalligudem,103906,―,Andhra Pradesh
317,318,Amaravati,103000,―,Andhra Pradesh
318,319,Buxar[34],102591,83168,Bihar
319,320,Tezpur,102505,83028,Assam
320,321,Jehanabad[35],102456,81503,Bihar
321,322,Aurangabad[36],101520,79393,Bihar
322,323,Gangtok,100286,29354,Sikkim
323,324,Vasco Da Gama,100000,―,Goa

In [10]:
All_Cities=dfs1
All_Cities

,Rank,Cities,Population(2011),Population(2001),State or Union Territory
0,1,Mumbai,12442373,11978450,Maharashtra
1,2,Delhi,11007835,9879172,Delhi
2,3,Bangalore,8425970,4301326,Karnataka
3,4,Hyderabad,6809970,3637483,Telangana
4,5,Ahmedabad,5570585,3520085,Gujarat
5,6,Chennai,4681087,4343645,Tamil Nadu
6,7,Kolkata,4486679,4572876,West Bengal
7,8,Surat,4467797,2433835,Gujarat
8,9,Pune,3115431,2538473,Maharashtra
9,10,Jaipur,3046163,2322575,Rajasthan
10,11,Lucknow,2815601,2185927,Uttar Pradesh
11,12,Kanpur,2767031,2551337,Uttar Pradesh
12,13,Nagpur,2405665,2052066,Maharashtra
13,14,Indore,1960631,1474968,Madhya Pradesh
14,15,Thane,1818872,1262551,Maharashtra
15,16,Bhopal,1795648,1437354,Madhya Pradesh
16,17,Visakhapatnam[4],1730320,1345938,Andhra Pradesh
17,18,Pimpri-Chinchwad,1727692,1012472,Maharashtra
18,19,Patna,1684222,1366444,Bihar
19,20,Vadodara,1670806,1306227,Gujarat
20,21,Ghaziabad,1648643,968256,Uttar Pradesh
21,22,Ludhiana,1618879,1398467,Punjab
22,23,Agra,1585704,1275134,Uttar Pradesh
23,24,Nashik,1486053,1077236,Maharashtra
24,25,Faridabad,1414050,1055938,Haryana
25,26,Meerut,1305429,1039405,Uttar Pradesh
26,27,Rajkot,1286678,967476,Gujarat
27,28,Kalyan-Dombivli,1247327,1193512,Maharashtra
28,29,Vasai-Virar,1222390,693350,Maharashtra
29,30,Varanasi,1201815,1091918,Uttar Pradesh
30,31,Srinagar,1180570,898440,Jammu and Kashmir
31,32,Aurangabad,1175116,873311,Maharashtra
32,33,Dhanbad,1162472,1065327,Jharkhand
33,34,Amritsar,1132383,966862,Punjab
34,35,Navi Mumbai,1120547,704002,Maharashtra
35,36,Allahabad,1112544,975393,Uttar Pradesh
36,37,Howrah,1077075,1007532,West Bengal
37,38,Ranchi,1073427,847093,Jharkhand
38,39,Gwalior,1069276,827026,Madhya Pradesh
39,40,Jabalpur,1055525,932484,Madhya Pradesh
40,41,Coimbatore,"1,050,721 [5]",930882,Tamil Nadu
41,42,Vijayawada,1034358,851282,Andhra Pradesh
42,43,Jodhpur,1033918,851051,Rajasthan
43,44,Madurai,1017865,928869,Tamil Nadu
44,45,Raipur,1010087,605747,Chhattisgarh
45,46,Kota[6],1001694,694316,Rajasthan
46,47,Chandigarh,960787,808515,Chandigarh
47,48,Guwahati,957352,809895,Assam
48,49,Solapur,951558,872478,Maharashtra
49,50,Hubli–Dharwad,943788,786195,Karnataka
50,51,Mysore[7][8][9],920550,762408,Karnataka
51,52,Tiruchirappalli[10],916674,752066,Tamil Nadu
52,53,Bareilly,898167,718395,Uttar Pradesh
53,54,Aligarh,889810,672315,Uttar Pradesh
54,55,Tiruppur,877778,344543,Tamil Nadu
55,56,Gurgaon,876824,173542,Haryana
56,57,Moradabad,872575,669087,Uttar Pradesh
57,58,Jalandhar,862196,706043,Punjab
58,59,Bhubaneswar,837737,648032,Odisha
59,60,Salem,831038,696760,Tamil Nadu
60,61,Warangal[11][12],830281,530636,Telangana
61,62,Mira-Bhayandar,814655,520388,Maharashtra
62,63,Jalgaon,798514,462280,Maharashtra
63,64,Guntur[13],670073,514461,Andhra Pradesh
64,65,Thiruvananthapuram,752490,368618,Kerala
65,66,Bhiwandi,711329,598741,Maharashtra
66,67,Saharanpur,703345,455754,Uttar Pradesh
67,68,Gorakhpur,671048,622701,Uttar Pradesh
68,69,Bikaner,647804,529690,Rajasthan
69,70,Amravati,646801,549510,Maharashtra
70,71,Noida,642381,305058,Uttar Pradesh
71,72,Jamshedpur,631364,573096,Jharkhand
72,73,Bhilai,625697,556366,Chhattisgarh
73,74,Cuttack,606007,534654,Odisha
74,75,Firozabad,603797,279102,Uttar Pradesh
75,76,Kochi,601574,596473,Kerala
76,77,Nellore[14][15],558548,378428,Andhra Pradesh
77,78,Bhavnagar,593768,511085,Gujarat
78,79,Dehradun,578420,426674,Uttarakhand
79,80,Durgapur,566937,493405,West Bengal
80,81,Asansol,564491,475439,West Bengal
81,82,Rourkela,552734,426354,Odisha
82,83,Nanded,550564,430733,Maharashtra
83,84,Kolhapur,549283,493167,Maharashtra
84,85,Ajmer,542580,485575,Rajasthan
85,86,Akola,537149,400520,Maharashtra
86,87,Gulbarga,532031,422569,Karnataka
87,88,Jamnagar,529308,443518,Gujarat
88,89,Ujjain,515215,430427,Madhya Pradesh
89,90,Loni,512296,120945,Uttar Pradesh
90,91,Siliguri,509709,472374,West Bengal
91,92,Jhansi,507293,383644,Uttar Pradesh
92,93,Ulhasnagar,506937,473731,Maharashtra
93,94,Jammu[16],503690,369959,Jammu and Kashmir
94,95,Sangli-Miraj & Kupwad,502697,436781,Maharashtra
95,96,Mangalore,499486,399565,Karnataka
96,97,Erode[17],498129,173600,Tamil Nadu
97,98,Belgaum,488292,399653,Karnataka
98,99,Kurnool[18],484327,345987,Andhra Pradesh
99,100,Ambattur,478134,310967,Tamil Nadu
100,101,Rajahmundry[19][20],476873,315251,Andhra Pradesh
101,102,Tirunelveli,473637,411831,Tamil Nadu
102,103,Malegaon,471006,409403,Maharashtra
103,104,Gaya,463454,385432,Bihar
104,105,Udaipur,451735,389438,Rajasthan
105,106,Karur,444506,158955,Tamil Nadu
106,107,Kakinada,443028,325985,Andhra Pradesh
107,108,Davanagere,435128,364523,Karnataka
108,109,Kozhikode,432097,436556,Kerala
109,110,Maheshtala,429423,385266,West Bengal
110,111,Rajpur Sonarpur,423806,336707,West Bengal
111,112,Bokaro,413934,393805,Jharkhand
112,113,South Dum Dum,410524,392444,West Bengal
113,114,Bellary,409644,316766,Karnataka
114,115,Patiala,405164,303151,Punjab
115,116,Gopalpur,404991,271811,West Bengal
116,117,Agartala,399688,271811,Tripura
117,118,Bhagalpur,398138,340767,Bihar
118,119,Muzaffarnagar,392451,316729,Uttar Pradesh
119,120,Bhatpara,390467,442385,West Bengal
120,121,Panihati,383522,348438,West Bengal
121,122,Latur,382754,299985,Maharashtra
122,123,Dhule,376093,341755,Maharashtra
123,124,Rohtak,373133,286807,Haryana
124,125,Sagar,370296,232133,Madhya Pradesh
125,126,Korba,363210,315690,Chhattisgarh
126,127,Bhilwara,360009,280128,Rajasthan
127,128,Berhampur,355823,307792,Odisha
128,129,Muzaffarpur,351838,305525,Bihar
129,130,Ahmednagar,350905,307615,Maharashtra
130,131,Mathura,349336,302770,Uttar Pradesh
131,132,Kollam,349033,361560,Kerala
132,133,Avadi,344701,229403,Tamil Nadu
133,134,Kadapa[21],344893,125725,Andhra Pradesh
134,135,Anantapuram[21],340613,255134,Andhra Pradesh
135,136,Kamarhati,336579,314507,West Bengal
136,137,Bilaspur,335761,296662,Chhattisgarh
137,138,Sambalpur,330106,274917,Odisha
138,139,Shahjahanpur,327975,296662,Uttar Pradesh
139,140,Satara,326789,228175,Maharashtra
140,141,Bijapur,326360,228175,Karnataka
141,142,Rampur,325248,281494,Uttar Pradesh
142,143,Shimoga,322428,274352,Karnataka
143,144,Chandrapur,321036,289450,Maharashtra
144,145,Junagadh,320250,168686,Gujarat
145,146,Thrissur,315596,317526,Kerala
146,147,Alwar,315310,260593,Rajasthan
147,148,Bardhaman,314638,285602,West Bengal
148,149,Kulti,313977,289903,West Bengal
149,150,Nizamabad,310467,288722,Telangana
150,151,Parbhani,307191,259329,Maharashtra
151,152,Tumkur,305821,248929,Karnataka
152,153,Khammam,305000,218689,Telangana
153,154,Uzhavarkarai,300028,217707,Puducherry
154,155,Bihar Sharif,296889,232071,Bihar
155,156,Panipat,294150,261740,Haryana
156,157,Darbhanga,294116,267348,Bihar
157,158,Bally,291972,260906,West Bengal
158,159,Aizawl,291822,228280,Mizoram
159,160,Dewas,289438,231672,Madhya Pradesh
160,161,Ichalkaranji,287570,257610,Maharashtra
161,162,Karnal,286974,210476,Haryana
162,163,Bathinda,285813,217256,Punjab
163,164,Jalna,285349,235795,Maharashtra
164,165,Eluru[22],283648,190347,Andhra Pradesh
165,166,Barasat,283443,231515,West Bengal
166,167,Kirari Suleman Nagar,282598,153874,Delhi
167,168,Purnia[23],280547,171687,Bihar
168,169,Satna,280248,225464,Madhya Pradesh
169,170,Mau,279060,212657,Uttar Pradesh
170,171,Sonipat,277053,214974,Haryana
171,172,Farrukhabad,275750,228333,Uttar Pradesh
172,173,Durg,268679,232517,Chhattisgarh
173,174,Imphal,264986,221492,Manipur
174,175,Ratlam,264810,222202,Madhya Pradesh
175,176,Hapur,262801,211983,Uttar Pradesh
176,177,Arrah,261099,203380,Bihar
177,178,Anantapur,261004,218808,Andhra Pradesh
178,179,Karimnagar,260899,205653,Telangana
179,180,Etawah,256838,210453,Uttar Pradesh
180,181,Ambarnath,254003,203795,Maharashtra
181,182,North Dum Dum,253625,220042,West Bengal
182,183,Bharatpur,252109,204587,Rajasthan
183,184,Begusarai,251136,93378,Bihar
184,185,New Delhi,249998,302147,Delhi
185,186,Gandhidham,248705,166388,Gujarat
186,187,Baranagar,248466,250768,West Bengal
187,188,Tiruvottiyur,248059,212281,Tamil Nadu
188,189,Pondicherry,241773,220749,Puducherry
189,190,Sikar,237579,184904,Rajasthan
190,191,Thoothukudi,237374,216058,Tamil Nadu
191,192,Rewa,235422,183274,Madhya Pradesh
192,193,Mirzapur,233691,205053,Uttar Pradesh
193,194,Raichur,232456,207421,Karnataka
194,195,Pali,229956,187641,Rajasthan
195,196,Ramagundam[24],229644,236600,Telangana
196,197,Silchar,229136,184105,Assam
197,198,Haridwar,228832,175010,Uttarakhand
198,199,Vijayanagaram,228025,174324,Andhra Pradesh
199,200,Tenali,225982,184937,Andhra Pradesh
200,201,Nagercoil,224849,208179,Tamil Nadu
201,202,Sri Ganganagar,224773,210713,Rajasthan
202,203,Karawal Nagar,224666,148549,Delhi
203,204,Mango,223805,166125,Jharkhand
204,205,Thanjavur,222943,215314,Tamil Nadu
205,206,Bulandshahr,222519,176425,Uttar Pradesh
206,207,Uluberia,222240,202135,West Bengal
207,208,Katni,221883,187029,Madhya Pradesh
208,209,Sambhal,220813,182478,Uttar Pradesh
209,210,Singrauli,220257,185190,Madhya Pradesh
210,211,Nadiad,218095,192913,Gujarat
211,212,Secunderabad,217910,206102,Telangana
212,213,Naihati,217900,215303,West Bengal
213,214,Yamunanagar,216677,189696,Haryana
214,215,Bidhannagar,215514,164221,West Bengal
215,216,Pallavaram,215417,144623,Tamil Nadu
216,217,Bidar,214373,172877,Karnataka
217,218,Munger,213303,188050,Bihar
218,219,Panchkula,211355,140925,Haryana
219,220,Burhanpur,210886,193725,Madhya Pradesh
220,221,Kharagpur,207604,188761,West Bengal
221,222,Dindigul,207327,196955,Tamil Nadu
222,223,Gandhinagar,206167,195985,Gujarat
223,224,Hospet,206167,164240,Karnataka
224,225,Nangloi Jat,205596,150948,Delhi
225,226,Malda,205521,161456,West Bengal
226,227,Ongole,204746,150471,Andhra Pradesh
227,228,Deoghar,203123,112525,Jharkhand
228,229,Chhapra,202352,79190,Bihar
229,230,Puri,201026,152682,Odisha
230,231,Haldia,200827,170673,West Bengal
231,232,Khandwa,200738,172242,Madhya Pradesh
232,233,Nandyal,200516,152676,Andhra Pradesh
233,234,Morena,200482,150959,Madhya Pradesh
234,235,Amroha,198471,165129,Uttar Pradesh
235,236,Anand,198282,130685,Gujarat
236,237,Bhind,197585,153752,Madhya Pradesh
237,238,Bhalswa Jahangir Pur,197148,152339,Delhi
238,239,Madhyamgram,196127,155451,West Bengal
239,240,Bhiwani,196057,169531,Haryana
240,241,Berhampore,195223,160143,West Bengal
241,242,Ambala,195153,139279,Haryana
242,243,Morbi,194947,145719,Gujarat
243,244,Fatehpur,193193,151757,Uttar Pradesh
244,245,Raebareli,191316,169333,Uttar Pradesh
245,246,"Khora, Ghaziabad",190400,―,Uttar Pradesh
246,247,Chittoor[25],189332,152654,Andhra Pradesh
247,248,Bhusawal,187421,172372,Maharashtra
248,249,Orai,187137,139318,Uttar Pradesh
249,250,Bahraich,186223,168323,Uttar Pradesh
250,251,Phusro,186139,83463,Jharkhand
251,252,Vellore,185803,177230,Tamil Nadu
252,253,Mehsana,184991,141453,Gujarat
253,254,Raiganj,183612,165212,West Bengal
254,255,Sirsa,182534,160735,Haryana
255,256,Danapur,182429,131176,Bihar
256,257,Serampore,181842,197857,West Bengal
257,258,Sultan Pur Majra,181554,164426,Delhi
258,259,Guna,180935,137175,Madhya Pradesh
259,260,Jaunpur,180362,160055,Uttar Pradesh
260,261,Panvel,180020,104058,Maharashtra
261,262,Shivpuri,179977,146892,Madhya Pradesh
262,263,Surendranagar Dudhrej,177851,156161,Gujarat
263,264,Unnao,177658,144662,Uttar Pradesh
264,265,Chinsurah,177259,170201,West Bengal
265,266,Alappuzha,174164,177029,Kerala
266,267,Kottayam,172878,129894,Kerala
267,268,Machilipatnam,169892,179353,Andhra Pradesh
268,269,Shimla,169578,142555,Himachal Pradesh
269,270,Midnapore,169127,149768,West Bengal
270,271,Adoni,166537,―,Andhra Pradesh
271,272,Udupi,165401,―,Karnataka
272,273,Katihar,164937,115169,Bihar
273,274,Proddatur,163600,86896,Andhra Pradesh
274,275,Budaun,159221,148029,Uttar Pradesh
275,276,Mahbubnagar,158000,–,Telangana
276,277,Saharsa[26],155175,125167,Bihar
277,278,Dibrugarh,154296,137661,Assam
278,279,Jorhat,153889,112026,Assam
279,280,Hazaribagh,153599,127243,Jharkhand
280,281,Hindupur,151835,―,Andhra Pradesh
281,282,Raigarh,150019,115908,Chhattisgarh
282,283,Nagaon,148496,123265,Assam
283,284,Hajipur[27],147688,119412,Bihar
284,285,Sasaram[28],147396,131172,Bihar
285,286,Giridih,143529,―,Jharkhand
286,287,Bhimavaram,142280,―,Andhra Pradesh
287,288,Port Blair,140572,—,Andaman and Nicobar Islands UT
288,289,Kumbakonam,140056,144021,Tamil Nadu
289,290,Bongaigaon,139650,101213,Assam
290,291,Dehri[28],137068,119057,Bihar
291,292,Madanapalle,135669,―,Andhra Pradesh
292,293,Siwan[29],134458,109919,Bihar
293,294,Bettiah[30],132896,116670,Bihar
294,295,Ramgarh,132441,73455,Jharkhand
295,296,Tinsukia,126389,101957,Assam
296,297,Guntakal,126270,―,Andhra Pradesh
297,298,Srikakulam,125939,―,Andhra Pradesh
298,299,Motihari[31],125183,100683,Bihar
299,300,Dharmavaram,121874,―,Andhra Pradesh
300,301,Medininagar,120325,―,Jharkhand
301,302,Gudivada,118167,―,Andhra Pradesh
302,303,Phagwara,117966,―,Punjab
303,304,Pudukkottai,117745,―,Tamil Nadu
304,305,Hosur,116821,102000,Tamil Nadu
305,306,Narasaraopet,116250,―,Andhra Pradesh
306,307,Suryapet,115250,94585,Telangana
307,308,Miryalaguda,109891,91395,Telangana
308,309,Anantnag,108505,―,Jammu and Kashmir
309,310,Tadipatri,108171,―,Andhra Pradesh
310,311,Karaikudi,106714,86596,Tamil Nadu
311,312,Kishanganj[32],105782,85590,Bihar
312,313,Gangavathi,105529,85459,Karnataka
313,314,Jamalpur[33],105221,96983,Bihar
314,315,Ballia,104271,―,Uttar Pradesh
315,316,Kavali,104000,―,Andhra Pradesh
316,317,Tadepalligudem,103906,―,Andhra Pradesh
317,318,Amaravati,103000,―,Andhra Pradesh
318,319,Buxar[34],102591,83168,Bihar
319,320,Tezpur,102505,83028,Assam
320,321,Jehanabad[35],102456,81503,Bihar
321,322,Aurangabad[36],101520,79393,Bihar
322,323,Gangtok,100286,29354,Sikkim
323,324,Vasco Da Gama,100000,―,Goa

In [11]:
dfs1.drop('Rank', inplace=True, axis=1) 
dfs1

,Cities,Population(2011),Population(2001),State or Union Territory
0,Mumbai,12442373,11978450,Maharashtra
1,Delhi,11007835,9879172,Delhi
2,Bangalore,8425970,4301326,Karnataka
3,Hyderabad,6809970,3637483,Telangana
4,Ahmedabad,5570585,3520085,Gujarat
5,Chennai,4681087,4343645,Tamil Nadu
6,Kolkata,4486679,4572876,West Bengal
7,Surat,4467797,2433835,Gujarat
8,Pune,3115431,2538473,Maharashtra
9,Jaipur,3046163,2322575,Rajasthan
10,Lucknow,2815601,2185927,Uttar Pradesh
11,Kanpur,2767031,2551337,Uttar Pradesh
12,Nagpur,2405665,2052066,Maharashtra
13,Indore,1960631,1474968,Madhya Pradesh
14,Thane,1818872,1262551,Maharashtra
15,Bhopal,1795648,1437354,Madhya Pradesh
16,Visakhapatnam[4],1730320,1345938,Andhra Pradesh
17,Pimpri-Chinchwad,1727692,1012472,Maharashtra
18,Patna,1684222,1366444,Bihar
19,Vadodara,1670806,1306227,Gujarat
20,Ghaziabad,1648643,968256,Uttar Pradesh
21,Ludhiana,1618879,1398467,Punjab
22,Agra,1585704,1275134,Uttar Pradesh
23,Nashik,1486053,1077236,Maharashtra
24,Faridabad,1414050,1055938,Haryana
25,Meerut,1305429,1039405,Uttar Pradesh
26,Rajkot,1286678,967476,Gujarat
27,Kalyan-Dombivli,1247327,1193512,Maharashtra
28,Vasai-Virar,1222390,693350,Maharashtra
29,Varanasi,1201815,1091918,Uttar Pradesh
30,Srinagar,1180570,898440,Jammu and Kashmir
31,Aurangabad,1175116,873311,Maharashtra
32,Dhanbad,1162472,1065327,Jharkhand
33,Amritsar,1132383,966862,Punjab
34,Navi Mumbai,1120547,704002,Maharashtra
35,Allahabad,1112544,975393,Uttar Pradesh
36,Howrah,1077075,1007532,West Bengal
37,Ranchi,1073427,847093,Jharkhand
38,Gwalior,1069276,827026,Madhya Pradesh
39,Jabalpur,1055525,932484,Madhya Pradesh
40,Coimbatore,"1,050,721 [5]",930882,Tamil Nadu
41,Vijayawada,1034358,851282,Andhra Pradesh
42,Jodhpur,1033918,851051,Rajasthan
43,Madurai,1017865,928869,Tamil Nadu
44,Raipur,1010087,605747,Chhattisgarh
45,Kota[6],1001694,694316,Rajasthan
46,Chandigarh,960787,808515,Chandigarh
47,Guwahati,957352,809895,Assam
48,Solapur,951558,872478,Maharashtra
49,Hubli–Dharwad,943788,786195,Karnataka
50,Mysore[7][8][9],920550,762408,Karnataka
51,Tiruchirappalli[10],916674,752066,Tamil Nadu
52,Bareilly,898167,718395,Uttar Pradesh
53,Aligarh,889810,672315,Uttar Pradesh
54,Tiruppur,877778,344543,Tamil Nadu
55,Gurgaon,876824,173542,Haryana
56,Moradabad,872575,669087,Uttar Pradesh
57,Jalandhar,862196,706043,Punjab
58,Bhubaneswar,837737,648032,Odisha
59,Salem,831038,696760,Tamil Nadu
60,Warangal[11][12],830281,530636,Telangana
61,Mira-Bhayandar,814655,520388,Maharashtra
62,Jalgaon,798514,462280,Maharashtra
63,Guntur[13],670073,514461,Andhra Pradesh
64,Thiruvananthapuram,752490,368618,Kerala
65,Bhiwandi,711329,598741,Maharashtra
66,Saharanpur,703345,455754,Uttar Pradesh
67,Gorakhpur,671048,622701,Uttar Pradesh
68,Bikaner,647804,529690,Rajasthan
69,Amravati,646801,549510,Maharashtra
70,Noida,642381,305058,Uttar Pradesh
71,Jamshedpur,631364,573096,Jharkhand
72,Bhilai,625697,556366,Chhattisgarh
73,Cuttack,606007,534654,Odisha
74,Firozabad,603797,279102,Uttar Pradesh
75,Kochi,601574,596473,Kerala
76,Nellore[14][15],558548,378428,Andhra Pradesh
77,Bhavnagar,593768,511085,Gujarat
78,Dehradun,578420,426674,Uttarakhand
79,Durgapur,566937,493405,West Bengal
80,Asansol,564491,475439,West Bengal
81,Rourkela,552734,426354,Odisha
82,Nanded,550564,430733,Maharashtra
83,Kolhapur,549283,493167,Maharashtra
84,Ajmer,542580,485575,Rajasthan
85,Akola,537149,400520,Maharashtra
86,Gulbarga,532031,422569,Karnataka
87,Jamnagar,529308,443518,Gujarat
88,Ujjain,515215,430427,Madhya Pradesh
89,Loni,512296,120945,Uttar Pradesh
90,Siliguri,509709,472374,West Bengal
91,Jhansi,507293,383644,Uttar Pradesh
92,Ulhasnagar,506937,473731,Maharashtra
93,Jammu[16],503690,369959,Jammu and Kashmir
94,Sangli-Miraj & Kupwad,502697,436781,Maharashtra
95,Mangalore,499486,399565,Karnataka
96,Erode[17],498129,173600,Tamil Nadu
97,Belgaum,488292,399653,Karnataka
98,Kurnool[18],484327,345987,Andhra Pradesh
99,Ambattur,478134,310967,Tamil Nadu
100,Rajahmundry[19][20],476873,315251,Andhra Pradesh
101,Tirunelveli,473637,411831,Tamil Nadu
102,Malegaon,471006,409403,Maharashtra
103,Gaya,463454,385432,Bihar
104,Udaipur,451735,389438,Rajasthan
105,Karur,444506,158955,Tamil Nadu
106,Kakinada,443028,325985,Andhra Pradesh
107,Davanagere,435128,364523,Karnataka
108,Kozhikode,432097,436556,Kerala
109,Maheshtala,429423,385266,West Bengal
110,Rajpur Sonarpur,423806,336707,West Bengal
111,Bokaro,413934,393805,Jharkhand
112,South Dum Dum,410524,392444,West Bengal
113,Bellary,409644,316766,Karnataka
114,Patiala,405164,303151,Punjab
115,Gopalpur,404991,271811,West Bengal
116,Agartala,399688,271811,Tripura
117,Bhagalpur,398138,340767,Bihar
118,Muzaffarnagar,392451,316729,Uttar Pradesh
119,Bhatpara,390467,442385,West Bengal
120,Panihati,383522,348438,West Bengal
121,Latur,382754,299985,Maharashtra
122,Dhule,376093,341755,Maharashtra
123,Rohtak,373133,286807,Haryana
124,Sagar,370296,232133,Madhya Pradesh
125,Korba,363210,315690,Chhattisgarh
126,Bhilwara,360009,280128,Rajasthan
127,Berhampur,355823,307792,Odisha
128,Muzaffarpur,351838,305525,Bihar
129,Ahmednagar,350905,307615,Maharashtra
130,Mathura,349336,302770,Uttar Pradesh
131,Kollam,349033,361560,Kerala
132,Avadi,344701,229403,Tamil Nadu
133,Kadapa[21],344893,125725,Andhra Pradesh
134,Anantapuram[21],340613,255134,Andhra Pradesh
135,Kamarhati,336579,314507,West Bengal
136,Bilaspur,335761,296662,Chhattisgarh
137,Sambalpur,330106,274917,Odisha
138,Shahjahanpur,327975,296662,Uttar Pradesh
139,Satara,326789,228175,Maharashtra
140,Bijapur,326360,228175,Karnataka
141,Rampur,325248,281494,Uttar Pradesh
142,Shimoga,322428,274352,Karnataka
143,Chandrapur,321036,289450,Maharashtra
144,Junagadh,320250,168686,Gujarat
145,Thrissur,315596,317526,Kerala
146,Alwar,315310,260593,Rajasthan
147,Bardhaman,314638,285602,West Bengal
148,Kulti,313977,289903,West Bengal
149,Nizamabad,310467,288722,Telangana
150,Parbhani,307191,259329,Maharashtra
151,Tumkur,305821,248929,Karnataka
152,Khammam,305000,218689,Telangana
153,Uzhavarkarai,300028,217707,Puducherry
154,Bihar Sharif,296889,232071,Bihar
155,Panipat,294150,261740,Haryana
156,Darbhanga,294116,267348,Bihar
157,Bally,291972,260906,West Bengal
158,Aizawl,291822,228280,Mizoram
159,Dewas,289438,231672,Madhya Pradesh
160,Ichalkaranji,287570,257610,Maharashtra
161,Karnal,286974,210476,Haryana
162,Bathinda,285813,217256,Punjab
163,Jalna,285349,235795,Maharashtra
164,Eluru[22],283648,190347,Andhra Pradesh
165,Barasat,283443,231515,West Bengal
166,Kirari Suleman Nagar,282598,153874,Delhi
167,Purnia[23],280547,171687,Bihar
168,Satna,280248,225464,Madhya Pradesh
169,Mau,279060,212657,Uttar Pradesh
170,Sonipat,277053,214974,Haryana
171,Farrukhabad,275750,228333,Uttar Pradesh
172,Durg,268679,232517,Chhattisgarh
173,Imphal,264986,221492,Manipur
174,Ratlam,264810,222202,Madhya Pradesh
175,Hapur,262801,211983,Uttar Pradesh
176,Arrah,261099,203380,Bihar
177,Anantapur,261004,218808,Andhra Pradesh
178,Karimnagar,260899,205653,Telangana
179,Etawah,256838,210453,Uttar Pradesh
180,Ambarnath,254003,203795,Maharashtra
181,North Dum Dum,253625,220042,West Bengal
182,Bharatpur,252109,204587,Rajasthan
183,Begusarai,251136,93378,Bihar
184,New Delhi,249998,302147,Delhi
185,Gandhidham,248705,166388,Gujarat
186,Baranagar,248466,250768,West Bengal
187,Tiruvottiyur,248059,212281,Tamil Nadu
188,Pondicherry,241773,220749,Puducherry
189,Sikar,237579,184904,Rajasthan
190,Thoothukudi,237374,216058,Tamil Nadu
191,Rewa,235422,183274,Madhya Pradesh
192,Mirzapur,233691,205053,Uttar Pradesh
193,Raichur,232456,207421,Karnataka
194,Pali,229956,187641,Rajasthan
195,Ramagundam[24],229644,236600,Telangana
196,Silchar,229136,184105,Assam
197,Haridwar,228832,175010,Uttarakhand
198,Vijayanagaram,228025,174324,Andhra Pradesh
199,Tenali,225982,184937,Andhra Pradesh
200,Nagercoil,224849,208179,Tamil Nadu
201,Sri Ganganagar,224773,210713,Rajasthan
202,Karawal Nagar,224666,148549,Delhi
203,Mango,223805,166125,Jharkhand
204,Thanjavur,222943,215314,Tamil Nadu
205,Bulandshahr,222519,176425,Uttar Pradesh
206,Uluberia,222240,202135,West Bengal
207,Katni,221883,187029,Madhya Pradesh
208,Sambhal,220813,182478,Uttar Pradesh
209,Singrauli,220257,185190,Madhya Pradesh
210,Nadiad,218095,192913,Gujarat
211,Secunderabad,217910,206102,Telangana
212,Naihati,217900,215303,West Bengal
213,Yamunanagar,216677,189696,Haryana
214,Bidhannagar,215514,164221,West Bengal
215,Pallavaram,215417,144623,Tamil Nadu
216,Bidar,214373,172877,Karnataka
217,Munger,213303,188050,Bihar
218,Panchkula,211355,140925,Haryana
219,Burhanpur,210886,193725,Madhya Pradesh
220,Kharagpur,207604,188761,West Bengal
221,Dindigul,207327,196955,Tamil Nadu
222,Gandhinagar,206167,195985,Gujarat
223,Hospet,206167,164240,Karnataka
224,Nangloi Jat,205596,150948,Delhi
225,Malda,205521,161456,West Bengal
226,Ongole,204746,150471,Andhra Pradesh
227,Deoghar,203123,112525,Jharkhand
228,Chhapra,202352,79190,Bihar
229,Puri,201026,152682,Odisha
230,Haldia,200827,170673,West Bengal
231,Khandwa,200738,172242,Madhya Pradesh
232,Nandyal,200516,152676,Andhra Pradesh
233,Morena,200482,150959,Madhya Pradesh
234,Amroha,198471,165129,Uttar Pradesh
235,Anand,198282,130685,Gujarat
236,Bhind,197585,153752,Madhya Pradesh
237,Bhalswa Jahangir Pur,197148,152339,Delhi
238,Madhyamgram,196127,155451,West Bengal
239,Bhiwani,196057,169531,Haryana
240,Berhampore,195223,160143,West Bengal
241,Ambala,195153,139279,Haryana
242,Morbi,194947,145719,Gujarat
243,Fatehpur,193193,151757,Uttar Pradesh
244,Raebareli,191316,169333,Uttar Pradesh
245,"Khora, Ghaziabad",190400,―,Uttar Pradesh
246,Chittoor[25],189332,152654,Andhra Pradesh
247,Bhusawal,187421,172372,Maharashtra
248,Orai,187137,139318,Uttar Pradesh
249,Bahraich,186223,168323,Uttar Pradesh
250,Phusro,186139,83463,Jharkhand
251,Vellore,185803,177230,Tamil Nadu
252,Mehsana,184991,141453,Gujarat
253,Raiganj,183612,165212,West Bengal
254,Sirsa,182534,160735,Haryana
255,Danapur,182429,131176,Bihar
256,Serampore,181842,197857,West Bengal
257,Sultan Pur Majra,181554,164426,Delhi
258,Guna,180935,137175,Madhya Pradesh
259,Jaunpur,180362,160055,Uttar Pradesh
260,Panvel,180020,104058,Maharashtra
261,Shivpuri,179977,146892,Madhya Pradesh
262,Surendranagar Dudhrej,177851,156161,Gujarat
263,Unnao,177658,144662,Uttar Pradesh
264,Chinsurah,177259,170201,West Bengal
265,Alappuzha,174164,177029,Kerala
266,Kottayam,172878,129894,Kerala
267,Machilipatnam,169892,179353,Andhra Pradesh
268,Shimla,169578,142555,Himachal Pradesh
269,Midnapore,169127,149768,West Bengal
270,Adoni,166537,―,Andhra Pradesh
271,Udupi,165401,―,Karnataka
272,Katihar,164937,115169,Bihar
273,Proddatur,163600,86896,Andhra Pradesh
274,Budaun,159221,148029,Uttar Pradesh
275,Mahbubnagar,158000,–,Telangana
276,Saharsa[26],155175,125167,Bihar
277,Dibrugarh,154296,137661,Assam
278,Jorhat,153889,112026,Assam
279,Hazaribagh,153599,127243,Jharkhand
280,Hindupur,151835,―,Andhra Pradesh
281,Raigarh,150019,115908,Chhattisgarh
282,Nagaon,148496,123265,Assam
283,Hajipur[27],147688,119412,Bihar
284,Sasaram[28],147396,131172,Bihar
285,Giridih,143529,―,Jharkhand
286,Bhimavaram,142280,―,Andhra Pradesh
287,Port Blair,140572,—,Andaman and Nicobar Islands UT
288,Kumbakonam,140056,144021,Tamil Nadu
289,Bongaigaon,139650,101213,Assam
290,Dehri[28],137068,119057,Bihar
291,Madanapalle,135669,―,Andhra Pradesh
292,Siwan[29],134458,109919,Bihar
293,Bettiah[30],132896,116670,Bihar
294,Ramgarh,132441,73455,Jharkhand
295,Tinsukia,126389,101957,Assam
296,Guntakal,126270,―,Andhra Pradesh
297,Srikakulam,125939,―,Andhra Pradesh
298,Motihari[31],125183,100683,Bihar
299,Dharmavaram,121874,―,Andhra Pradesh
300,Medininagar,120325,―,Jharkhand
301,Gudivada,118167,―,Andhra Pradesh
302,Phagwara,117966,―,Punjab
303,Pudukkottai,117745,―,Tamil Nadu
304,Hosur,116821,102000,Tamil Nadu
305,Narasaraopet,116250,―,Andhra Pradesh
306,Suryapet,115250,94585,Telangana
307,Miryalaguda,109891,91395,Telangana
308,Anantnag,108505,―,Jammu and Kashmir
309,Tadipatri,108171,―,Andhra Pradesh
310,Karaikudi,106714,86596,Tamil Nadu
311,Kishanganj[32],105782,85590,Bihar
312,Gangavathi,105529,85459,Karnataka
313,Jamalpur[33],105221,96983,Bihar
314,Ballia,104271,―,Uttar Pradesh
315,Kavali,104000,―,Andhra Pradesh
316,Tadepalligudem,103906,―,Andhra Pradesh
317,Amaravati,103000,―,Andhra Pradesh
318,Buxar[34],102591,83168,Bihar
319,Tezpur,102505,83028,Assam
320,Jehanabad[35],102456,81503,Bihar
321,Aurangabad[36],101520,79393,Bihar
322,Gangtok,100286,29354,Sikkim
323,Vasco Da Gama,100000,―,Goa

In [12]:
# dfs1['Population(2001)'] = dfs1['Population(2001)'].replace({'_': ''}, regex=True)
# print(dfs1)

In [13]:
dfs1.index

RangeIndex(start=0, stop=324, step=1)

In [14]:
dfs1.index +=1
dfs1.index

RangeIndex(start=1, stop=325, step=1)

In [15]:
dfs1.head()

      Cities Population(2011) Population(2001) State or Union Territory
1     Mumbai         12442373         11978450              Maharashtra
2      Delhi         11007835          9879172                    Delhi
3  Bangalore          8425970          4301326                Karnataka
4  Hyderabad          6809970          3637483                Telangana
5  Ahmedabad          5570585          3520085                  Gujarat

In [16]:
dfs1["Population(2001)"]=dfs1["Population(2001)"].str.replace(r'\W',"unknown")
dfs1

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2291681525.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  dfs1["Population(2001)"]=dfs1["Population(2001)"].str.replace(r'\W',"unknown")

,Cities,Population(2011),Population(2001),State or Union Territory
1,Mumbai,12442373,11978450,Maharashtra
2,Delhi,11007835,9879172,Delhi
3,Bangalore,8425970,4301326,Karnataka
4,Hyderabad,6809970,3637483,Telangana
5,Ahmedabad,5570585,3520085,Gujarat
6,Chennai,4681087,4343645,Tamil Nadu
7,Kolkata,4486679,4572876,West Bengal
8,Surat,4467797,2433835,Gujarat
9,Pune,3115431,2538473,Maharashtra
10,Jaipur,3046163,2322575,Rajasthan
11,Lucknow,2815601,2185927,Uttar Pradesh
12,Kanpur,2767031,2551337,Uttar Pradesh
13,Nagpur,2405665,2052066,Maharashtra
14,Indore,1960631,1474968,Madhya Pradesh
15,Thane,1818872,1262551,Maharashtra
16,Bhopal,1795648,1437354,Madhya Pradesh
17,Visakhapatnam[4],1730320,1345938,Andhra Pradesh
18,Pimpri-Chinchwad,1727692,1012472,Maharashtra
19,Patna,1684222,1366444,Bihar
20,Vadodara,1670806,1306227,Gujarat
21,Ghaziabad,1648643,968256,Uttar Pradesh
22,Ludhiana,1618879,1398467,Punjab
23,Agra,1585704,1275134,Uttar Pradesh
24,Nashik,1486053,1077236,Maharashtra
25,Faridabad,1414050,1055938,Haryana
26,Meerut,1305429,1039405,Uttar Pradesh
27,Rajkot,1286678,967476,Gujarat
28,Kalyan-Dombivli,1247327,1193512,Maharashtra
29,Vasai-Virar,1222390,693350,Maharashtra
30,Varanasi,1201815,1091918,Uttar Pradesh
31,Srinagar,1180570,898440,Jammu and Kashmir
32,Aurangabad,1175116,873311,Maharashtra
33,Dhanbad,1162472,1065327,Jharkhand
34,Amritsar,1132383,966862,Punjab
35,Navi Mumbai,1120547,704002,Maharashtra
36,Allahabad,1112544,975393,Uttar Pradesh
37,Howrah,1077075,1007532,West Bengal
38,Ranchi,1073427,847093,Jharkhand
39,Gwalior,1069276,827026,Madhya Pradesh
40,Jabalpur,1055525,932484,Madhya Pradesh
41,Coimbatore,"1,050,721 [5]",930882,Tamil Nadu
42,Vijayawada,1034358,851282,Andhra Pradesh
43,Jodhpur,1033918,851051,Rajasthan
44,Madurai,1017865,928869,Tamil Nadu
45,Raipur,1010087,605747,Chhattisgarh
46,Kota[6],1001694,694316,Rajasthan
47,Chandigarh,960787,808515,Chandigarh
48,Guwahati,957352,809895,Assam
49,Solapur,951558,872478,Maharashtra
50,Hubli–Dharwad,943788,786195,Karnataka
51,Mysore[7][8][9],920550,762408,Karnataka
52,Tiruchirappalli[10],916674,752066,Tamil Nadu
53,Bareilly,898167,718395,Uttar Pradesh
54,Aligarh,889810,672315,Uttar Pradesh
55,Tiruppur,877778,344543,Tamil Nadu
56,Gurgaon,876824,173542,Haryana
57,Moradabad,872575,669087,Uttar Pradesh
58,Jalandhar,862196,706043,Punjab
59,Bhubaneswar,837737,648032,Odisha
60,Salem,831038,696760,Tamil Nadu
61,Warangal[11][12],830281,530636,Telangana
62,Mira-Bhayandar,814655,520388,Maharashtra
63,Jalgaon,798514,462280,Maharashtra
64,Guntur[13],670073,514461,Andhra Pradesh
65,Thiruvananthapuram,752490,368618,Kerala
66,Bhiwandi,711329,598741,Maharashtra
67,Saharanpur,703345,455754,Uttar Pradesh
68,Gorakhpur,671048,622701,Uttar Pradesh
69,Bikaner,647804,529690,Rajasthan
70,Amravati,646801,549510,Maharashtra
71,Noida,642381,305058,Uttar Pradesh
72,Jamshedpur,631364,573096,Jharkhand
73,Bhilai,625697,556366,Chhattisgarh
74,Cuttack,606007,534654,Odisha
75,Firozabad,603797,279102,Uttar Pradesh
76,Kochi,601574,596473,Kerala
77,Nellore[14][15],558548,378428,Andhra Pradesh
78,Bhavnagar,593768,511085,Gujarat
79,Dehradun,578420,426674,Uttarakhand
80,Durgapur,566937,493405,West Bengal
81,Asansol,564491,475439,West Bengal
82,Rourkela,552734,426354,Odisha
83,Nanded,550564,430733,Maharashtra
84,Kolhapur,549283,493167,Maharashtra
85,Ajmer,542580,485575,Rajasthan
86,Akola,537149,400520,Maharashtra
87,Gulbarga,532031,422569,Karnataka
88,Jamnagar,529308,443518,Gujarat
89,Ujjain,515215,430427,Madhya Pradesh
90,Loni,512296,120945,Uttar Pradesh
91,Siliguri,509709,472374,West Bengal
92,Jhansi,507293,383644,Uttar Pradesh
93,Ulhasnagar,506937,473731,Maharashtra
94,Jammu[16],503690,369959,Jammu and Kashmir
95,Sangli-Miraj & Kupwad,502697,436781,Maharashtra
96,Mangalore,499486,399565,Karnataka
97,Erode[17],498129,173600,Tamil Nadu
98,Belgaum,488292,399653,Karnataka
99,Kurnool[18],484327,345987,Andhra Pradesh
100,Ambattur,478134,310967,Tamil Nadu
101,Rajahmundry[19][20],476873,315251,Andhra Pradesh
102,Tirunelveli,473637,411831,Tamil Nadu
103,Malegaon,471006,409403,Maharashtra
104,Gaya,463454,385432,Bihar
105,Udaipur,451735,389438,Rajasthan
106,Karur,444506,158955,Tamil Nadu
107,Kakinada,443028,325985,Andhra Pradesh
108,Davanagere,435128,364523,Karnataka
109,Kozhikode,432097,436556,Kerala
110,Maheshtala,429423,385266,West Bengal
111,Rajpur Sonarpur,423806,336707,West Bengal
112,Bokaro,413934,393805,Jharkhand
113,South Dum Dum,410524,392444,West Bengal
114,Bellary,409644,316766,Karnataka
115,Patiala,405164,303151,Punjab
116,Gopalpur,404991,271811,West Bengal
117,Agartala,399688,271811,Tripura
118,Bhagalpur,398138,340767,Bihar
119,Muzaffarnagar,392451,316729,Uttar Pradesh
120,Bhatpara,390467,442385,West Bengal
121,Panihati,383522,348438,West Bengal
122,Latur,382754,299985,Maharashtra
123,Dhule,376093,341755,Maharashtra
124,Rohtak,373133,286807,Haryana
125,Sagar,370296,232133,Madhya Pradesh
126,Korba,363210,315690,Chhattisgarh
127,Bhilwara,360009,280128,Rajasthan
128,Berhampur,355823,307792,Odisha
129,Muzaffarpur,351838,305525,Bihar
130,Ahmednagar,350905,307615,Maharashtra
131,Mathura,349336,302770,Uttar Pradesh
132,Kollam,349033,361560,Kerala
133,Avadi,344701,229403,Tamil Nadu
134,Kadapa[21],344893,125725,Andhra Pradesh
135,Anantapuram[21],340613,255134,Andhra Pradesh
136,Kamarhati,336579,314507,West Bengal
137,Bilaspur,335761,296662,Chhattisgarh
138,Sambalpur,330106,274917,Odisha
139,Shahjahanpur,327975,296662,Uttar Pradesh
140,Satara,326789,228175,Maharashtra
141,Bijapur,326360,228175,Karnataka
142,Rampur,325248,281494,Uttar Pradesh
143,Shimoga,322428,274352,Karnataka
144,Chandrapur,321036,289450,Maharashtra
145,Junagadh,320250,168686,Gujarat
146,Thrissur,315596,317526,Kerala
147,Alwar,315310,260593,Rajasthan
148,Bardhaman,314638,285602,West Bengal
149,Kulti,313977,289903,West Bengal
150,Nizamabad,310467,288722,Telangana
151,Parbhani,307191,259329,Maharashtra
152,Tumkur,305821,248929,Karnataka
153,Khammam,305000,218689,Telangana
154,Uzhavarkarai,300028,217707,Puducherry
155,Bihar Sharif,296889,232071,Bihar
156,Panipat,294150,261740,Haryana
157,Darbhanga,294116,267348,Bihar
158,Bally,291972,260906,West Bengal
159,Aizawl,291822,228280,Mizoram
160,Dewas,289438,231672,Madhya Pradesh
161,Ichalkaranji,287570,257610,Maharashtra
162,Karnal,286974,210476,Haryana
163,Bathinda,285813,217256,Punjab
164,Jalna,285349,235795,Maharashtra
165,Eluru[22],283648,190347,Andhra Pradesh
166,Barasat,283443,231515,West Bengal
167,Kirari Suleman Nagar,282598,153874,Delhi
168,Purnia[23],280547,171687,Bihar
169,Satna,280248,225464,Madhya Pradesh
170,Mau,279060,212657,Uttar Pradesh
171,Sonipat,277053,214974,Haryana
172,Farrukhabad,275750,228333,Uttar Pradesh
173,Durg,268679,232517,Chhattisgarh
174,Imphal,264986,221492,Manipur
175,Ratlam,264810,222202,Madhya Pradesh
176,Hapur,262801,211983,Uttar Pradesh
177,Arrah,261099,203380,Bihar
178,Anantapur,261004,218808,Andhra Pradesh
179,Karimnagar,260899,205653,Telangana
180,Etawah,256838,210453,Uttar Pradesh
181,Ambarnath,254003,203795,Maharashtra
182,North Dum Dum,253625,220042,West Bengal
183,Bharatpur,252109,204587,Rajasthan
184,Begusarai,251136,93378,Bihar
185,New Delhi,249998,302147,Delhi
186,Gandhidham,248705,166388,Gujarat
187,Baranagar,248466,250768,West Bengal
188,Tiruvottiyur,248059,212281,Tamil Nadu
189,Pondicherry,241773,220749,Puducherry
190,Sikar,237579,184904,Rajasthan
191,Thoothukudi,237374,216058,Tamil Nadu
192,Rewa,235422,183274,Madhya Pradesh
193,Mirzapur,233691,205053,Uttar Pradesh
194,Raichur,232456,207421,Karnataka
195,Pali,229956,187641,Rajasthan
196,Ramagundam[24],229644,236600,Telangana
197,Silchar,229136,184105,Assam
198,Haridwar,228832,175010,Uttarakhand
199,Vijayanagaram,228025,174324,Andhra Pradesh
200,Tenali,225982,184937,Andhra Pradesh
201,Nagercoil,224849,208179,Tamil Nadu
202,Sri Ganganagar,224773,210713,Rajasthan
203,Karawal Nagar,224666,148549,Delhi
204,Mango,223805,166125,Jharkhand
205,Thanjavur,222943,215314,Tamil Nadu
206,Bulandshahr,222519,176425,Uttar Pradesh
207,Uluberia,222240,202135,West Bengal
208,Katni,221883,187029,Madhya Pradesh
209,Sambhal,220813,182478,Uttar Pradesh
210,Singrauli,220257,185190,Madhya Pradesh
211,Nadiad,218095,192913,Gujarat
212,Secunderabad,217910,206102,Telangana
213,Naihati,217900,215303,West Bengal
214,Yamunanagar,216677,189696,Haryana
215,Bidhannagar,215514,164221,West Bengal
216,Pallavaram,215417,144623,Tamil Nadu
217,Bidar,214373,172877,Karnataka
218,Munger,213303,188050,Bihar
219,Panchkula,211355,140925,Haryana
220,Burhanpur,210886,193725,Madhya Pradesh
221,Kharagpur,207604,188761,West Bengal
222,Dindigul,207327,196955,Tamil Nadu
223,Gandhinagar,206167,195985,Gujarat
224,Hospet,206167,164240,Karnataka
225,Nangloi Jat,205596,150948,Delhi
226,Malda,205521,161456,West Bengal
227,Ongole,204746,150471,Andhra Pradesh
228,Deoghar,203123,112525,Jharkhand
229,Chhapra,202352,79190,Bihar
230,Puri,201026,152682,Odisha
231,Haldia,200827,170673,West Bengal
232,Khandwa,200738,172242,Madhya Pradesh
233,Nandyal,200516,152676,Andhra Pradesh
234,Morena,200482,150959,Madhya Pradesh
235,Amroha,198471,165129,Uttar Pradesh
236,Anand,198282,130685,Gujarat
237,Bhind,197585,153752,Madhya Pradesh
238,Bhalswa Jahangir Pur,197148,152339,Delhi
239,Madhyamgram,196127,155451,West Bengal
240,Bhiwani,196057,169531,Haryana
241,Berhampore,195223,160143,West Bengal
242,Ambala,195153,139279,Haryana
243,Morbi,194947,145719,Gujarat
244,Fatehpur,193193,151757,Uttar Pradesh
245,Raebareli,191316,169333,Uttar Pradesh
246,"Khora, Ghaziabad",190400,unknown,Uttar Pradesh
247,Chittoor[25],189332,152654,Andhra Pradesh
248,Bhusawal,187421,172372,Maharashtra
249,Orai,187137,139318,Uttar Pradesh
250,Bahraich,186223,168323,Uttar Pradesh
251,Phusro,186139,83463,Jharkhand
252,Vellore,185803,177230,Tamil Nadu
253,Mehsana,184991,141453,Gujarat
254,Raiganj,183612,165212,West Bengal
255,Sirsa,182534,160735,Haryana
256,Danapur,182429,131176,Bihar
257,Serampore,181842,197857,West Bengal
258,Sultan Pur Majra,181554,164426,Delhi
259,Guna,180935,137175,Madhya Pradesh
260,Jaunpur,180362,160055,Uttar Pradesh
261,Panvel,180020,104058,Maharashtra
262,Shivpuri,179977,146892,Madhya Pradesh
263,Surendranagar Dudhrej,177851,156161,Gujarat
264,Unnao,177658,144662,Uttar Pradesh
265,Chinsurah,177259,170201,West Bengal
266,Alappuzha,174164,177029,Kerala
267,Kottayam,172878,129894,Kerala
268,Machilipatnam,169892,179353,Andhra Pradesh
269,Shimla,169578,142555,Himachal Pradesh
270,Midnapore,169127,149768,West Bengal
271,Adoni,166537,unknown,Andhra Pradesh
272,Udupi,165401,unknown,Karnataka
273,Katihar,164937,115169,Bihar
274,Proddatur,163600,86896,Andhra Pradesh
275,Budaun,159221,148029,Uttar Pradesh
276,Mahbubnagar,158000,unknown,Telangana
277,Saharsa[26],155175,125167,Bihar
278,Dibrugarh,154296,137661,Assam
279,Jorhat,153889,112026,Assam
280,Hazaribagh,153599,127243,Jharkhand
281,Hindupur,151835,unknown,Andhra Pradesh
282,Raigarh,150019,115908,Chhattisgarh
283,Nagaon,148496,123265,Assam
284,Hajipur[27],147688,119412,Bihar
285,Sasaram[28],147396,131172,Bihar
286,Giridih,143529,unknown,Jharkhand
287,Bhimavaram,142280,unknown,Andhra Pradesh
288,Port Blair,140572,unknown,Andaman and Nicobar Islands UT
289,Kumbakonam,140056,144021,Tamil Nadu
290,Bongaigaon,139650,101213,Assam
291,Dehri[28],137068,119057,Bihar
292,Madanapalle,135669,unknown,Andhra Pradesh
293,Siwan[29],134458,109919,Bihar
294,Bettiah[30],132896,116670,Bihar
295,Ramgarh,132441,73455,Jharkhand
296,Tinsukia,126389,101957,Assam
297,Guntakal,126270,unknown,Andhra Pradesh
298,Srikakulam,125939,unknown,Andhra Pradesh
299,Motihari[31],125183,100683,Bihar
300,Dharmavaram,121874,unknown,Andhra Pradesh
301,Medininagar,120325,unknown,Jharkhand
302,Gudivada,118167,unknown,Andhra Pradesh
303,Phagwara,117966,unknown,Punjab
304,Pudukkottai,117745,unknown,Tamil Nadu
305,Hosur,116821,102000,Tamil Nadu
306,Narasaraopet,116250,unknown,Andhra Pradesh
307,Suryapet,115250,94585,Telangana
308,Miryalaguda,109891,91395,Telangana
309,Anantnag,108505,unknown,Jammu and Kashmir
310,Tadipatri,108171,unknown,Andhra Pradesh
311,Karaikudi,106714,86596,Tamil Nadu
312,Kishanganj[32],105782,85590,Bihar
313,Gangavathi,105529,85459,Karnataka
314,Jamalpur[33],105221,96983,Bihar
315,Ballia,104271,unknown,Uttar Pradesh
316,Kavali,104000,unknown,Andhra Pradesh
317,Tadepalligudem,103906,unknown,Andhra Pradesh
318,Amaravati,103000,unknown,Andhra Pradesh
319,Buxar[34],102591,83168,Bihar
320,Tezpur,102505,83028,Assam
321,Jehanabad[35],102456,81503,Bihar
322,Aurangabad[36],101520,79393,Bihar
323,Gangtok,100286,29354,Sikkim
324,Vasco Da Gama,100000,unknown,Goa

In [17]:
dfs1["Population(2001)"].describe()

count         324
unique        298
top       unknown
freq           24
Name: Population(2001), dtype: object

In [18]:
pd.value_counts(dfs1["Population(2001)"])

unknown     24
271811       2
296662       2
228175       2
11978450     1
208179       1
176425       1
215314       1
166125       1
148549       1
210713       1
184937       1
174324       1
175010       1
184105       1
236600       1
187641       1
207421       1
205053       1
202135       1
182478       1
187029       1
216058       1
164240       1
195985       1
196955       1
188761       1
193725       1
140925       1
188050       1
172877       1
144623       1
164221       1
189696       1
215303       1
206102       1
192913       1
185190       1
183274       1
220749       1
184904       1
235795       1
212657       1
225464       1
171687       1
153874       1
231515       1
190347       1
217256       1
228333       1
210476       1
257610       1
231672       1
228280       1
260906       1
267348       1
214974       1
232517       1
161456       1
220042       1
212281       1
250768       1
166388       1
302147       1
93378        1
204587       1
203795       1
221492       1
210453       1
205653       1
218808       1
203380       1
211983       1
222202       1
150948       1
150471       1
232071       1
101213       1
131172       1
119412       1
123265       1
115908       1
127243       1
112026       1
137661       1
125167       1
148029       1
86896        1
115169       1
149768       1
142555       1
179353       1
129894       1
144021       1
119057       1
112525       1
109919       1
79393        1
81503        1
83028        1
83168        1
96983        1
85459        1
85590        1
86596        1
91395        1
94585        1
102000       1
100683       1
101957       1
73455        1
116670       1
177029       1
170201       1
144662       1
156161       1
145719       1
139279       1
160143       1
169531       1
155451       1
152339       1
153752       1
130685       1
165129       1
150959       1
152676       1
172242       1
170673       1
152682       1
79190        1
151757       1
169333       1
152654       1
131176       1
146892       1
104058       1
160055       1
137175       1
164426       1
197857       1
160735       1
172372       1
165212       1
141453       1
177230       1
83463        1
168323       1
139318       1
261740       1
218689       1
217707       1
847093       1
672315       1
718395       1
752066       1
762408       1
786195       1
872478       1
809895       1
808515       1
694316       1
605747       1
928869       1
851051       1
851282       1
930882       1
932484       1
344543       1
173542       1
669087       1
598741       1
573096       1
305058       1
549510       1
529690       1
622701       1
455754       1
368618       1
706043       1
514461       1
462280       1
520388       1
530636       1
696760       1
648032       1
827026       1
1007532      1
534654       1
975393       1
1345938      1
1437354      1
1262551      1
1474968      1
2052066      1
2551337      1
2185927      1
2322575      1
2538473      1
2433835      1
4572876      1
4343645      1
3520085      1
3637483      1
4301326      1
1012472      1
1366444      1
1306227      1
693350       1
704002       1
966862       1
1065327      1
873311       1
898440       1
1091918      1
1193512      1
968256       1
967476       1
1039405      1
1055938      1
1077236      1
1275134      1
1398467      1
556366       1
279102       1
9879172      1
393805       1
307615       1
305525       1
307792       1
280128       1
315690       1
232133       1
286807       1
341755       1
299985       1
348438       1
442385       1
316729       1
340767       1
303151       1
316766       1
302770       1
361560       1
229403       1
317526       1
248929       1
259329       1
288722       1
289903       1
285602       1
260593       1
168686       1
125725       1
289450       1
274352       1
281494       1
274917       1
314507       1
255134       1
392444       1
336707       1
596473       1
385266       1
472374       1
120945       1
430427       1
443518       1
422569       1
400520       1
485575       1
493167       1
430733       1
426354       1
475439       1
493405       1
426674       1
511085       1
378428       1
383644       1
473731       1
369959       1
409403       1
436556       1
364523       1
325985       1
158955       1
389438       1
385432       1
411831       1
436781       1
315251       1
310967       1
345987       1
399653       1
173600       1
399565       1
29354        1
Name: Population(2001), dtype: int64

In [19]:
df1=dfs1[dfs1['Population(2001)']== "unknown"]
display(dfs1[dfs1['Population(2001)']== "unknown"])

,Cities,Population(2011),Population(2001),State or Union Territory
246,"Khora, Ghaziabad",190400,unknown,Uttar Pradesh
271,Adoni,166537,unknown,Andhra Pradesh
272,Udupi,165401,unknown,Karnataka
276,Mahbubnagar,158000,unknown,Telangana
281,Hindupur,151835,unknown,Andhra Pradesh
286,Giridih,143529,unknown,Jharkhand
287,Bhimavaram,142280,unknown,Andhra Pradesh
288,Port Blair,140572,unknown,Andaman and Nicobar Islands UT
292,Madanapalle,135669,unknown,Andhra Pradesh
297,Guntakal,126270,unknown,Andhra Pradesh
298,Srikakulam,125939,unknown,Andhra Pradesh
300,Dharmavaram,121874,unknown,Andhra Pradesh
301,Medininagar,120325,unknown,Jharkhand
302,Gudivada,118167,unknown,Andhra Pradesh
303,Phagwara,117966,unknown,Punjab
304,Pudukkottai,117745,unknown,Tamil Nadu
306,Narasaraopet,116250,unknown,Andhra Pradesh
309,Anantnag,108505,unknown,Jammu and Kashmir
310,Tadipatri,108171,unknown,Andhra Pradesh
315,Ballia,104271,unknown,Uttar Pradesh
316,Kavali,104000,unknown,Andhra Pradesh
317,Tadepalligudem,103906,unknown,Andhra Pradesh
318,Amaravati,103000,unknown,Andhra Pradesh
324,Vasco Da Gama,100000,unknown,Goa

In [20]:
dfs1.to_csv("unknown population(2001).csv")

In [21]:
df2=dfs1[dfs1['Population(2001)']== '271811' ]
display(dfs1[dfs1['Population(2001)']=='271811'  ])

       Cities Population(2011) Population(2001) State or Union Territory
116  Gopalpur           404991           271811              West Bengal
117  Agartala           399688           271811                  Tripura

In [22]:
pd.value_counts(dfs1["State or Union Territory"])

Uttar Pradesh                     37
Maharashtra                       32
Andhra Pradesh                    31
West Bengal                       30
Bihar                             25
Tamil Nadu                        22
Madhya Pradesh                    18
Karnataka                         16
Gujarat                           14
Rajasthan                         12
Haryana                           11
Jharkhand                         11
Telangana                         10
Assam                              8
Delhi                              7
Kerala                             7
Punjab                             6
Chhattisgarh                       6
Odisha                             6
Jammu and Kashmir                  3
Puducherry                         2
Uttarakhand                        2
Tripura                            1
Chandigarh                         1
Mizoram                            1
Manipur                            1
Himachal Pradesh                   1
Andaman and Nicobar Islands UT     1
Sikkim                             1
Goa                                1
Name: State or Union Territory, dtype: int64

In [23]:
len(dfs1['State or Union Territory'])# total number of cities

324

In [24]:
State_or_Union_Territory_count = dfs1["State or Union Territory"].value_counts()
State_or_Union_Territory_count

Uttar Pradesh                     37
Maharashtra                       32
Andhra Pradesh                    31
West Bengal                       30
Bihar                             25
Tamil Nadu                        22
Madhya Pradesh                    18
Karnataka                         16
Gujarat                           14
Rajasthan                         12
Haryana                           11
Jharkhand                         11
Telangana                         10
Assam                              8
Delhi                              7
Kerala                             7
Punjab                             6
Chhattisgarh                       6
Odisha                             6
Jammu and Kashmir                  3
Puducherry                         2
Uttarakhand                        2
Tripura                            1
Chandigarh                         1
Mizoram                            1
Manipur                            1
Himachal Pradesh                   1
Andaman and Nicobar Islands UT     1
Sikkim                             1
Goa                                1
Name: State or Union Territory, dtype: int64

In [25]:
len(State_or_Union_Territory_count)

30

In [26]:
 dfs1.to_csv("Statewise cities count.csv")

In [27]:
df2=dfs1[dfs1['State or Union Territory']== 'Uttar Pradesh' ]
display(dfs1[dfs1["State or Union Territory"]=='Uttar Pradesh' ])

,Cities,Population(2011),Population(2001),State or Union Territory
11,Lucknow,2815601,2185927,Uttar Pradesh
12,Kanpur,2767031,2551337,Uttar Pradesh
21,Ghaziabad,1648643,968256,Uttar Pradesh
23,Agra,1585704,1275134,Uttar Pradesh
26,Meerut,1305429,1039405,Uttar Pradesh
30,Varanasi,1201815,1091918,Uttar Pradesh
36,Allahabad,1112544,975393,Uttar Pradesh
53,Bareilly,898167,718395,Uttar Pradesh
54,Aligarh,889810,672315,Uttar Pradesh
57,Moradabad,872575,669087,Uttar Pradesh
67,Saharanpur,703345,455754,Uttar Pradesh
68,Gorakhpur,671048,622701,Uttar Pradesh
71,Noida,642381,305058,Uttar Pradesh
75,Firozabad,603797,279102,Uttar Pradesh
90,Loni,512296,120945,Uttar Pradesh
92,Jhansi,507293,383644,Uttar Pradesh
119,Muzaffarnagar,392451,316729,Uttar Pradesh
131,Mathura,349336,302770,Uttar Pradesh
139,Shahjahanpur,327975,296662,Uttar Pradesh
142,Rampur,325248,281494,Uttar Pradesh
170,Mau,279060,212657,Uttar Pradesh
172,Farrukhabad,275750,228333,Uttar Pradesh
176,Hapur,262801,211983,Uttar Pradesh
180,Etawah,256838,210453,Uttar Pradesh
193,Mirzapur,233691,205053,Uttar Pradesh
206,Bulandshahr,222519,176425,Uttar Pradesh
209,Sambhal,220813,182478,Uttar Pradesh
235,Amroha,198471,165129,Uttar Pradesh
244,Fatehpur,193193,151757,Uttar Pradesh
245,Raebareli,191316,169333,Uttar Pradesh
246,"Khora, Ghaziabad",190400,unknown,Uttar Pradesh
249,Orai,187137,139318,Uttar Pradesh
250,Bahraich,186223,168323,Uttar Pradesh
260,Jaunpur,180362,160055,Uttar Pradesh
264,Unnao,177658,144662,Uttar Pradesh
275,Budaun,159221,148029,Uttar Pradesh
315,Ballia,104271,unknown,Uttar Pradesh

In [28]:
df21=df2.drop('State or Union Territory', inplace=True, axis=1) 
df21

C:\Users\home\AppData\Local\Temp\ipykernel_18300\4070880256.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df21=df2.drop('State or Union Territory', inplace=True, axis=1)

In [29]:
Uttar_Pradesh=df2
Uttar_Pradesh

               Cities Population(2011) Population(2001)
11            Lucknow          2815601          2185927
12             Kanpur          2767031          2551337
21          Ghaziabad          1648643           968256
23               Agra          1585704          1275134
26             Meerut          1305429          1039405
30           Varanasi          1201815          1091918
36          Allahabad          1112544           975393
53           Bareilly           898167           718395
54            Aligarh           889810           672315
57          Moradabad           872575           669087
67         Saharanpur           703345           455754
68          Gorakhpur           671048           622701
71              Noida           642381           305058
75          Firozabad           603797           279102
90               Loni           512296           120945
92             Jhansi           507293           383644
119     Muzaffarnagar           392451           316729
131           Mathura           349336           302770
139      Shahjahanpur           327975           296662
142            Rampur           325248           281494
170               Mau           279060           212657
172       Farrukhabad           275750           228333
176             Hapur           262801           211983
180            Etawah           256838           210453
193          Mirzapur           233691           205053
206       Bulandshahr           222519           176425
209           Sambhal           220813           182478
235            Amroha           198471           165129
244          Fatehpur           193193           151757
245         Raebareli           191316           169333
246  Khora, Ghaziabad           190400          unknown
249              Orai           187137           139318
250          Bahraich           186223           168323
260           Jaunpur           180362           160055
264             Unnao           177658           144662
275            Budaun           159221           148029
315            Ballia           104271          unknown

In [30]:
Uttar_Pradesh.index

Int64Index([ 11,  12,  21,  23,  26,  30,  36,  53,  54,  57,  67,  68,  71,
             75,  90,  92, 119, 131, 139, 142, 170, 172, 176, 180, 193, 206,
            209, 235, 244, 245, 246, 249, 250, 260, 264, 275, 315],
           dtype='int64')

In [31]:
len(Uttar_Pradesh)

37

In [32]:
mean_rank=(11+12+21+23+26+30+36+53+54+57+67+68+71+
             75+90+92+119+131+139+142+170+172+176+180+193+206+
            209+235+244+245+246+249+250+260+264+275+315)/37
Uttar_Pradesh_mean_rank=mean_rank
Uttar_Pradesh_mean_rank

140.7027027027027

In [33]:
df3=dfs1[dfs1['State or Union Territory']== 'Maharashtra' ]
display(dfs1[dfs1["State or Union Territory"]=='Maharashtra' ])

,Cities,Population(2011),Population(2001),State or Union Territory
1,Mumbai,12442373,11978450,Maharashtra
9,Pune,3115431,2538473,Maharashtra
13,Nagpur,2405665,2052066,Maharashtra
15,Thane,1818872,1262551,Maharashtra
18,Pimpri-Chinchwad,1727692,1012472,Maharashtra
24,Nashik,1486053,1077236,Maharashtra
28,Kalyan-Dombivli,1247327,1193512,Maharashtra
29,Vasai-Virar,1222390,693350,Maharashtra
32,Aurangabad,1175116,873311,Maharashtra
35,Navi Mumbai,1120547,704002,Maharashtra
49,Solapur,951558,872478,Maharashtra
62,Mira-Bhayandar,814655,520388,Maharashtra
63,Jalgaon,798514,462280,Maharashtra
66,Bhiwandi,711329,598741,Maharashtra
70,Amravati,646801,549510,Maharashtra
83,Nanded,550564,430733,Maharashtra
84,Kolhapur,549283,493167,Maharashtra
86,Akola,537149,400520,Maharashtra
93,Ulhasnagar,506937,473731,Maharashtra
95,Sangli-Miraj & Kupwad,502697,436781,Maharashtra
103,Malegaon,471006,409403,Maharashtra
122,Latur,382754,299985,Maharashtra
123,Dhule,376093,341755,Maharashtra
130,Ahmednagar,350905,307615,Maharashtra
140,Satara,326789,228175,Maharashtra
144,Chandrapur,321036,289450,Maharashtra
151,Parbhani,307191,259329,Maharashtra
161,Ichalkaranji,287570,257610,Maharashtra
164,Jalna,285349,235795,Maharashtra
181,Ambarnath,254003,203795,Maharashtra
248,Bhusawal,187421,172372,Maharashtra
261,Panvel,180020,104058,Maharashtra

In [34]:
df31=df3.drop('State or Union Territory', inplace=True, axis=1) 
df31

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2896687831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df31=df3.drop('State or Union Territory', inplace=True, axis=1)

In [35]:
Maharashtra=df3
Maharashtra

                    Cities Population(2011) Population(2001)
1                   Mumbai         12442373         11978450
9                     Pune          3115431          2538473
13                  Nagpur          2405665          2052066
15                   Thane          1818872          1262551
18        Pimpri-Chinchwad          1727692          1012472
24                  Nashik          1486053          1077236
28         Kalyan-Dombivli          1247327          1193512
29             Vasai-Virar          1222390           693350
32              Aurangabad          1175116           873311
35             Navi Mumbai          1120547           704002
49                 Solapur           951558           872478
62          Mira-Bhayandar           814655           520388
63                 Jalgaon           798514           462280
66                Bhiwandi           711329           598741
70                Amravati           646801           549510
83                  Nanded           550564           430733
84                Kolhapur           549283           493167
86                   Akola           537149           400520
93              Ulhasnagar           506937           473731
95   Sangli-Miraj & Kupwad           502697           436781
103               Malegaon           471006           409403
122                  Latur           382754           299985
123                  Dhule           376093           341755
130             Ahmednagar           350905           307615
140                 Satara           326789           228175
144             Chandrapur           321036           289450
151               Parbhani           307191           259329
161           Ichalkaranji           287570           257610
164                  Jalna           285349           235795
181              Ambarnath           254003           203795
248               Bhusawal           187421           172372
261                 Panvel           180020           104058

In [36]:
Maharashtra.index

Int64Index([  1,   9,  13,  15,  18,  24,  28,  29,  32,  35,  49,  62,  63,
             66,  70,  83,  84,  86,  93,  95, 103, 122, 123, 130, 140, 144,
            151, 161, 164, 181, 248, 261],
           dtype='int64')

In [37]:
len(Maharashtra.index)

32

In [38]:
mean_rank=(1+9+13+15+18+24+28+29+32+35+49+62+63+
             66+70+83+84+86+93+95+103+122+123+130+140+144+
            151+161+164+181+248+261)/32
Maharashtra_mean_rank=mean_rank
Maharashtra_mean_rank

90.09375

In [39]:
df4=dfs1[dfs1['State or Union Territory']== 'Andhra Pradesh' ]
display(dfs1[dfs1["State or Union Territory"]=='Andhra Pradesh' ])

,Cities,Population(2011),Population(2001),State or Union Territory
17,Visakhapatnam[4],1730320,1345938,Andhra Pradesh
42,Vijayawada,1034358,851282,Andhra Pradesh
64,Guntur[13],670073,514461,Andhra Pradesh
77,Nellore[14][15],558548,378428,Andhra Pradesh
99,Kurnool[18],484327,345987,Andhra Pradesh
101,Rajahmundry[19][20],476873,315251,Andhra Pradesh
107,Kakinada,443028,325985,Andhra Pradesh
134,Kadapa[21],344893,125725,Andhra Pradesh
135,Anantapuram[21],340613,255134,Andhra Pradesh
165,Eluru[22],283648,190347,Andhra Pradesh
178,Anantapur,261004,218808,Andhra Pradesh
199,Vijayanagaram,228025,174324,Andhra Pradesh
200,Tenali,225982,184937,Andhra Pradesh
227,Ongole,204746,150471,Andhra Pradesh
233,Nandyal,200516,152676,Andhra Pradesh
247,Chittoor[25],189332,152654,Andhra Pradesh
268,Machilipatnam,169892,179353,Andhra Pradesh
271,Adoni,166537,unknown,Andhra Pradesh
274,Proddatur,163600,86896,Andhra Pradesh
281,Hindupur,151835,unknown,Andhra Pradesh
287,Bhimavaram,142280,unknown,Andhra Pradesh
292,Madanapalle,135669,unknown,Andhra Pradesh
297,Guntakal,126270,unknown,Andhra Pradesh
298,Srikakulam,125939,unknown,Andhra Pradesh
300,Dharmavaram,121874,unknown,Andhra Pradesh
302,Gudivada,118167,unknown,Andhra Pradesh
306,Narasaraopet,116250,unknown,Andhra Pradesh
310,Tadipatri,108171,unknown,Andhra Pradesh
316,Kavali,104000,unknown,Andhra Pradesh
317,Tadepalligudem,103906,unknown,Andhra Pradesh
318,Amaravati,103000,unknown,Andhra Pradesh

In [40]:
df41=df4.drop('State or Union Territory', inplace=True, axis=1) 
df41

C:\Users\home\AppData\Local\Temp\ipykernel_18300\1634104756.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df41=df4.drop('State or Union Territory', inplace=True, axis=1)

In [41]:
Andhra_Pradesh=df4
Andhra_Pradesh

                  Cities Population(2011) Population(2001)
17      Visakhapatnam[4]          1730320          1345938
42            Vijayawada          1034358           851282
64            Guntur[13]           670073           514461
77       Nellore[14][15]           558548           378428
99           Kurnool[18]           484327           345987
101  Rajahmundry[19][20]           476873           315251
107             Kakinada           443028           325985
134           Kadapa[21]           344893           125725
135      Anantapuram[21]           340613           255134
165            Eluru[22]           283648           190347
178            Anantapur           261004           218808
199        Vijayanagaram           228025           174324
200               Tenali           225982           184937
227               Ongole           204746           150471
233              Nandyal           200516           152676
247         Chittoor[25]           189332           152654
268        Machilipatnam           169892           179353
271                Adoni           166537          unknown
274            Proddatur           163600            86896
281             Hindupur           151835          unknown
287           Bhimavaram           142280          unknown
292          Madanapalle           135669          unknown
297             Guntakal           126270          unknown
298           Srikakulam           125939          unknown
300          Dharmavaram           121874          unknown
302             Gudivada           118167          unknown
306         Narasaraopet           116250          unknown
310            Tadipatri           108171          unknown
316               Kavali           104000          unknown
317       Tadepalligudem           103906          unknown
318            Amaravati           103000          unknown

In [42]:
Andhra_Pradesh.index

Int64Index([ 17,  42,  64,  77,  99, 101, 107, 134, 135, 165, 178, 199, 200,
            227, 233, 247, 268, 271, 274, 281, 287, 292, 297, 298, 300, 302,
            306, 310, 316, 317, 318],
           dtype='int64')

In [43]:
len(Andhra_Pradesh.index)

31

In [44]:
mean_rank=(17+42+64+77+99+101+107+134+135+165+178+199+200+
            227+233+247+268+271+274+281+287+292+297+298+300+302+
            306+310+316+317+318)/31
Andhra_Pradesh_mean_rank=mean_rank
Andhra_Pradesh_mean_rank

214.90322580645162

In [45]:
df5=dfs1[dfs1['State or Union Territory']== 'West Bengal' ]
display(dfs1[dfs1["State or Union Territory"]=='West Bengal' ])

,Cities,Population(2011),Population(2001),State or Union Territory
7,Kolkata,4486679,4572876,West Bengal
37,Howrah,1077075,1007532,West Bengal
80,Durgapur,566937,493405,West Bengal
81,Asansol,564491,475439,West Bengal
91,Siliguri,509709,472374,West Bengal
110,Maheshtala,429423,385266,West Bengal
111,Rajpur Sonarpur,423806,336707,West Bengal
113,South Dum Dum,410524,392444,West Bengal
116,Gopalpur,404991,271811,West Bengal
120,Bhatpara,390467,442385,West Bengal
121,Panihati,383522,348438,West Bengal
136,Kamarhati,336579,314507,West Bengal
148,Bardhaman,314638,285602,West Bengal
149,Kulti,313977,289903,West Bengal
158,Bally,291972,260906,West Bengal
166,Barasat,283443,231515,West Bengal
182,North Dum Dum,253625,220042,West Bengal
187,Baranagar,248466,250768,West Bengal
207,Uluberia,222240,202135,West Bengal
213,Naihati,217900,215303,West Bengal
215,Bidhannagar,215514,164221,West Bengal
221,Kharagpur,207604,188761,West Bengal
226,Malda,205521,161456,West Bengal
231,Haldia,200827,170673,West Bengal
239,Madhyamgram,196127,155451,West Bengal
241,Berhampore,195223,160143,West Bengal
254,Raiganj,183612,165212,West Bengal
257,Serampore,181842,197857,West Bengal
265,Chinsurah,177259,170201,West Bengal
270,Midnapore,169127,149768,West Bengal

In [46]:
df51=df5.drop('State or Union Territory', inplace=True, axis=1) 
df51

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2256690138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df51=df5.drop('State or Union Territory', inplace=True, axis=1)

In [47]:
West_Bengal=df5
West_Bengal

              Cities Population(2011) Population(2001)
7            Kolkata          4486679          4572876
37            Howrah          1077075          1007532
80          Durgapur           566937           493405
81           Asansol           564491           475439
91          Siliguri           509709           472374
110       Maheshtala           429423           385266
111  Rajpur Sonarpur           423806           336707
113    South Dum Dum           410524           392444
116         Gopalpur           404991           271811
120         Bhatpara           390467           442385
121         Panihati           383522           348438
136        Kamarhati           336579           314507
148        Bardhaman           314638           285602
149            Kulti           313977           289903
158            Bally           291972           260906
166          Barasat           283443           231515
182    North Dum Dum           253625           220042
187        Baranagar           248466           250768
207         Uluberia           222240           202135
213          Naihati           217900           215303
215      Bidhannagar           215514           164221
221        Kharagpur           207604           188761
226            Malda           205521           161456
231           Haldia           200827           170673
239      Madhyamgram           196127           155451
241       Berhampore           195223           160143
254          Raiganj           183612           165212
257        Serampore           181842           197857
265        Chinsurah           177259           170201
270        Midnapore           169127           149768

In [48]:
West_Bengal.index

Int64Index([  7,  37,  80,  81,  91, 110, 111, 113, 116, 120, 121, 136, 148,
            149, 158, 166, 182, 187, 207, 213, 215, 221, 226, 231, 239, 241,
            254, 257, 265, 270],
           dtype='int64')

In [49]:
len(West_Bengal.index)

30

In [50]:
mean_rank=(7+37+80+81+91+110+111+113+116+120+121+136+148+
            149+158+166+182+187+207+213+215+221+226+231+239+241+
            254+257+265+270)/30
West_Bengal_mean_rank=mean_rank
West_Bengal_mean_rank

165.06666666666666

In [51]:
df6=dfs1[dfs1['State or Union Territory']== 'Bihar' ]
display(dfs1[dfs1["State or Union Territory"]=='Bihar' ])

             Cities Population(2011) Population(2001) State or Union Territory
19            Patna          1684222          1366444                    Bihar
104            Gaya           463454           385432                    Bihar
118       Bhagalpur           398138           340767                    Bihar
129     Muzaffarpur           351838           305525                    Bihar
155    Bihar Sharif           296889           232071                    Bihar
157       Darbhanga           294116           267348                    Bihar
168      Purnia[23]           280547           171687                    Bihar
177           Arrah           261099           203380                    Bihar
184       Begusarai           251136            93378                    Bihar
218          Munger           213303           188050                    Bihar
229         Chhapra           202352            79190                    Bihar
256         Danapur           182429           131176                    Bihar
273         Katihar           164937           115169                    Bihar
277     Saharsa[26]           155175           125167                    Bihar
284     Hajipur[27]           147688           119412                    Bihar
285     Sasaram[28]           147396           131172                    Bihar
291       Dehri[28]           137068           119057                    Bihar
293       Siwan[29]           134458           109919                    Bihar
294     Bettiah[30]           132896           116670                    Bihar
299    Motihari[31]           125183           100683                    Bihar
312  Kishanganj[32]           105782            85590                    Bihar
314    Jamalpur[33]           105221            96983                    Bihar
319       Buxar[34]           102591            83168                    Bihar
321   Jehanabad[35]           102456            81503                    Bihar
322  Aurangabad[36]           101520            79393                    Bihar

In [52]:
df61=df6.drop('State or Union Territory', inplace=True, axis=1) 
df61

C:\Users\home\AppData\Local\Temp\ipykernel_18300\606070816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df61=df6.drop('State or Union Territory', inplace=True, axis=1)

In [53]:
Bihar=df6
Bihar

             Cities Population(2011) Population(2001)
19            Patna          1684222          1366444
104            Gaya           463454           385432
118       Bhagalpur           398138           340767
129     Muzaffarpur           351838           305525
155    Bihar Sharif           296889           232071
157       Darbhanga           294116           267348
168      Purnia[23]           280547           171687
177           Arrah           261099           203380
184       Begusarai           251136            93378
218          Munger           213303           188050
229         Chhapra           202352            79190
256         Danapur           182429           131176
273         Katihar           164937           115169
277     Saharsa[26]           155175           125167
284     Hajipur[27]           147688           119412
285     Sasaram[28]           147396           131172
291       Dehri[28]           137068           119057
293       Siwan[29]           134458           109919
294     Bettiah[30]           132896           116670
299    Motihari[31]           125183           100683
312  Kishanganj[32]           105782            85590
314    Jamalpur[33]           105221            96983
319       Buxar[34]           102591            83168
321   Jehanabad[35]           102456            81503
322  Aurangabad[36]           101520            79393

In [54]:
Bihar.index

Int64Index([ 19, 104, 118, 129, 155, 157, 168, 177, 184, 218, 229, 256, 273,
            277, 284, 285, 291, 293, 294, 299, 312, 314, 319, 321, 322],
           dtype='int64')

In [55]:
len(Bihar.index)

25

In [56]:
mean_rank=( 7+42+45+53+56+61+98+101+103+107+134+189+192+
            202+206+217+223+253+290+305+306+312)/25
Bihar_mean_rank=mean_rank
Bihar_mean_rank

140.08

In [57]:
df6=dfs1[dfs1['State or Union Territory']== 'Tamil Nadu' ]
display(dfs1[dfs1["State or Union Territory"]=='Tamil Nadu' ])

,Cities,Population(2011),Population(2001),State or Union Territory
6,Chennai,4681087,4343645,Tamil Nadu
41,Coimbatore,"1,050,721 [5]",930882,Tamil Nadu
44,Madurai,1017865,928869,Tamil Nadu
52,Tiruchirappalli[10],916674,752066,Tamil Nadu
55,Tiruppur,877778,344543,Tamil Nadu
60,Salem,831038,696760,Tamil Nadu
97,Erode[17],498129,173600,Tamil Nadu
100,Ambattur,478134,310967,Tamil Nadu
102,Tirunelveli,473637,411831,Tamil Nadu
106,Karur,444506,158955,Tamil Nadu
133,Avadi,344701,229403,Tamil Nadu
188,Tiruvottiyur,248059,212281,Tamil Nadu
191,Thoothukudi,237374,216058,Tamil Nadu
201,Nagercoil,224849,208179,Tamil Nadu
205,Thanjavur,222943,215314,Tamil Nadu
216,Pallavaram,215417,144623,Tamil Nadu
222,Dindigul,207327,196955,Tamil Nadu
252,Vellore,185803,177230,Tamil Nadu
289,Kumbakonam,140056,144021,Tamil Nadu
304,Pudukkottai,117745,unknown,Tamil Nadu
305,Hosur,116821,102000,Tamil Nadu
311,Karaikudi,106714,86596,Tamil Nadu

In [58]:
df61=df6.drop('State or Union Territory', inplace=True, axis=1) 
df61

C:\Users\home\AppData\Local\Temp\ipykernel_18300\606070816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df61=df6.drop('State or Union Territory', inplace=True, axis=1)

In [59]:
Tamil_Nadu=df6
Tamil_Nadu

                  Cities Population(2011) Population(2001)
6                Chennai          4681087          4343645
41            Coimbatore    1,050,721 [5]           930882
44               Madurai          1017865           928869
52   Tiruchirappalli[10]           916674           752066
55              Tiruppur           877778           344543
60                 Salem           831038           696760
97             Erode[17]           498129           173600
100             Ambattur           478134           310967
102          Tirunelveli           473637           411831
106                Karur           444506           158955
133                Avadi           344701           229403
188         Tiruvottiyur           248059           212281
191          Thoothukudi           237374           216058
201            Nagercoil           224849           208179
205            Thanjavur           222943           215314
216           Pallavaram           215417           144623
222             Dindigul           207327           196955
252              Vellore           185803           177230
289           Kumbakonam           140056           144021
304          Pudukkottai           117745          unknown
305                Hosur           116821           102000
311            Karaikudi           106714            86596

In [60]:
Tamil_Nadu.index

Int64Index([  6,  41,  44,  52,  55,  60,  97, 100, 102, 106, 133, 188, 191,
            201, 205, 216, 222, 252, 289, 304, 305, 311],
           dtype='int64')

In [61]:
len(Tamil_Nadu.index)

22

In [62]:
mean_rank=(7+42+45+53+56+61+98+101+103+107+134+189+192+
            202+206+217+223+253+290+305+306+312)/22
Tamil_Nadu_mean_rank=mean_rank
Tamil_Nadu_mean_rank

159.1818181818182

In [63]:
df7=dfs1[dfs1['State or Union Territory']== 'Madhya Pradesh' ]
display(dfs1[dfs1["State or Union Territory"]=='Madhya Pradesh' ])

        Cities Population(2011) Population(2001) State or Union Territory
14      Indore          1960631          1474968           Madhya Pradesh
16      Bhopal          1795648          1437354           Madhya Pradesh
39     Gwalior          1069276           827026           Madhya Pradesh
40    Jabalpur          1055525           932484           Madhya Pradesh
89      Ujjain           515215           430427           Madhya Pradesh
125      Sagar           370296           232133           Madhya Pradesh
160      Dewas           289438           231672           Madhya Pradesh
169      Satna           280248           225464           Madhya Pradesh
175     Ratlam           264810           222202           Madhya Pradesh
192       Rewa           235422           183274           Madhya Pradesh
208      Katni           221883           187029           Madhya Pradesh
210  Singrauli           220257           185190           Madhya Pradesh
220  Burhanpur           210886           193725           Madhya Pradesh
232    Khandwa           200738           172242           Madhya Pradesh
234     Morena           200482           150959           Madhya Pradesh
237      Bhind           197585           153752           Madhya Pradesh
259       Guna           180935           137175           Madhya Pradesh
262   Shivpuri           179977           146892           Madhya Pradesh

In [64]:
df71=df7.drop('State or Union Territory', inplace=True, axis=1) 
df71

C:\Users\home\AppData\Local\Temp\ipykernel_18300\3981683594.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df71=df7.drop('State or Union Territory', inplace=True, axis=1)

In [65]:
Madhya_Pradesh=df7
Madhya_Pradesh

        Cities Population(2011) Population(2001)
14      Indore          1960631          1474968
16      Bhopal          1795648          1437354
39     Gwalior          1069276           827026
40    Jabalpur          1055525           932484
89      Ujjain           515215           430427
125      Sagar           370296           232133
160      Dewas           289438           231672
169      Satna           280248           225464
175     Ratlam           264810           222202
192       Rewa           235422           183274
208      Katni           221883           187029
210  Singrauli           220257           185190
220  Burhanpur           210886           193725
232    Khandwa           200738           172242
234     Morena           200482           150959
237      Bhind           197585           153752
259       Guna           180935           137175
262   Shivpuri           179977           146892

In [66]:
Madhya_Pradesh.index

Int64Index([ 14,  16,  39,  40,  89, 125, 160, 169, 175, 192, 208, 210, 220,
            232, 234, 237, 259, 262],
           dtype='int64')

In [67]:
len(Madhya_Pradesh.index)

18

In [68]:
mean_rank=(15+17+40+41+90+126+161+170+176+193+209+211+221+
            233+235+238+260+263)/18
Madhya_Pradesh_mean_rank=mean_rank
Madhya_Pradesh_mean_rank

161.05555555555554

In [69]:
df8=dfs1[dfs1['State or Union Territory']== 'Karnataka' ]
display(dfs1[dfs1["State or Union Territory"]=='Karnataka' ])



# df.reset_index(level=0, inplace=True)
# df

,Cities,Population(2011),Population(2001),State or Union Territory
3,Bangalore,8425970,4301326,Karnataka
50,Hubli–Dharwad,943788,786195,Karnataka
51,Mysore[7][8][9],920550,762408,Karnataka
87,Gulbarga,532031,422569,Karnataka
96,Mangalore,499486,399565,Karnataka
98,Belgaum,488292,399653,Karnataka
108,Davanagere,435128,364523,Karnataka
114,Bellary,409644,316766,Karnataka
141,Bijapur,326360,228175,Karnataka
143,Shimoga,322428,274352,Karnataka
152,Tumkur,305821,248929,Karnataka
194,Raichur,232456,207421,Karnataka
217,Bidar,214373,172877,Karnataka
224,Hospet,206167,164240,Karnataka
272,Udupi,165401,unknown,Karnataka
313,Gangavathi,105529,85459,Karnataka

In [70]:
df81=df8.drop('State or Union Territory', inplace=True, axis=1) 
df81

C:\Users\home\AppData\Local\Temp\ipykernel_18300\485206630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df81=df8.drop('State or Union Territory', inplace=True, axis=1)

In [71]:
Karnataka=df8
Karnataka

              Cities Population(2011) Population(2001)
3          Bangalore          8425970          4301326
50     Hubli–Dharwad           943788           786195
51   Mysore[7][8][9]           920550           762408
87          Gulbarga           532031           422569
96         Mangalore           499486           399565
98           Belgaum           488292           399653
108       Davanagere           435128           364523
114          Bellary           409644           316766
141          Bijapur           326360           228175
143          Shimoga           322428           274352
152           Tumkur           305821           248929
194          Raichur           232456           207421
217            Bidar           214373           172877
224           Hospet           206167           164240
272            Udupi           165401          unknown
313       Gangavathi           105529            85459

In [72]:
Karnataka.index

Int64Index([3, 50, 51, 87, 96, 98, 108, 114, 141, 143, 152, 194, 217, 224, 272,
            313],
           dtype='int64')

In [73]:
len(Karnataka.index)

16

In [74]:
mean_rank=(4+51+52+88+97+99+109+115+142+144+153+195+218+225+273+
            314)/16
Karnataka_mean_rank=mean_rank
Karnataka_mean_rank

142.4375

In [75]:
df9=dfs1[dfs1['State or Union Territory']== 'Gujarat' ]
display(dfs1[dfs1["State or Union Territory"]=='Gujarat' ])

,Cities,Population(2011),Population(2001),State or Union Territory
5,Ahmedabad,5570585,3520085,Gujarat
8,Surat,4467797,2433835,Gujarat
20,Vadodara,1670806,1306227,Gujarat
27,Rajkot,1286678,967476,Gujarat
78,Bhavnagar,593768,511085,Gujarat
88,Jamnagar,529308,443518,Gujarat
145,Junagadh,320250,168686,Gujarat
186,Gandhidham,248705,166388,Gujarat
211,Nadiad,218095,192913,Gujarat
223,Gandhinagar,206167,195985,Gujarat
236,Anand,198282,130685,Gujarat
243,Morbi,194947,145719,Gujarat
253,Mehsana,184991,141453,Gujarat
263,Surendranagar Dudhrej,177851,156161,Gujarat

In [76]:
df91=df9.drop('State or Union Territory', inplace=True, axis=1) 
df91

C:\Users\home\AppData\Local\Temp\ipykernel_18300\1554271898.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df91=df9.drop('State or Union Territory', inplace=True, axis=1)

In [77]:
Gujarat=df9
Gujarat

                    Cities Population(2011) Population(2001)
5                Ahmedabad          5570585          3520085
8                    Surat          4467797          2433835
20                Vadodara          1670806          1306227
27                  Rajkot          1286678           967476
78               Bhavnagar           593768           511085
88                Jamnagar           529308           443518
145               Junagadh           320250           168686
186             Gandhidham           248705           166388
211                 Nadiad           218095           192913
223            Gandhinagar           206167           195985
236                  Anand           198282           130685
243                  Morbi           194947           145719
253                Mehsana           184991           141453
263  Surendranagar Dudhrej           177851           156161

In [78]:
Gujarat.index

Int64Index([5, 8, 20, 27, 78, 88, 145, 186, 211, 223, 236, 243, 253, 263], dtype='int64')

In [79]:
len(Gujarat.index)

14

In [80]:
mean_rank=(6+9+21+28+79+89+146+187+212+224+237+244+254+264)/14
Gujarat_mean_rank=mean_rank
Gujarat_mean_rank

142.85714285714286

In [81]:
df10=dfs1[dfs1['State or Union Territory']== 'Rajasthan' ]
display(dfs1[dfs1["State or Union Territory"]=='Rajasthan' ])

             Cities Population(2011) Population(2001) State or Union Territory
10           Jaipur          3046163          2322575                Rajasthan
43          Jodhpur          1033918           851051                Rajasthan
46          Kota[6]          1001694           694316                Rajasthan
69          Bikaner           647804           529690                Rajasthan
85            Ajmer           542580           485575                Rajasthan
105         Udaipur           451735           389438                Rajasthan
127        Bhilwara           360009           280128                Rajasthan
147           Alwar           315310           260593                Rajasthan
183       Bharatpur           252109           204587                Rajasthan
190           Sikar           237579           184904                Rajasthan
195            Pali           229956           187641                Rajasthan
202  Sri Ganganagar           224773           210713                Rajasthan

In [82]:
df101=df10.drop('State or Union Territory', inplace=True, axis=1) 
df101

C:\Users\home\AppData\Local\Temp\ipykernel_18300\4249277154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df101=df10.drop('State or Union Territory', inplace=True, axis=1)

In [83]:
Rajasthan=df10
df10

             Cities Population(2011) Population(2001)
10           Jaipur          3046163          2322575
43          Jodhpur          1033918           851051
46          Kota[6]          1001694           694316
69          Bikaner           647804           529690
85            Ajmer           542580           485575
105         Udaipur           451735           389438
127        Bhilwara           360009           280128
147           Alwar           315310           260593
183       Bharatpur           252109           204587
190           Sikar           237579           184904
195            Pali           229956           187641
202  Sri Ganganagar           224773           210713

In [84]:
Rajasthan.index

Int64Index([10, 43, 46, 69, 85, 105, 127, 147, 183, 190, 195, 202], dtype='int64')

In [85]:
len(Rajasthan.index)

12

In [86]:
mean_rank=(11+44+47+70+86+106+128+148+184+191+196+203)/12
Rajasthan_mean_rank=mean_rank
Rajasthan_mean_rank

117.83333333333333

In [87]:
df11=dfs1[dfs1['State or Union Territory']== 'Haryana' ]
display(dfs1[dfs1["State or Union Territory"]=='Haryana' ])

          Cities Population(2011) Population(2001) State or Union Territory
25     Faridabad          1414050          1055938                  Haryana
56       Gurgaon           876824           173542                  Haryana
124       Rohtak           373133           286807                  Haryana
156      Panipat           294150           261740                  Haryana
162       Karnal           286974           210476                  Haryana
171      Sonipat           277053           214974                  Haryana
214  Yamunanagar           216677           189696                  Haryana
219    Panchkula           211355           140925                  Haryana
240      Bhiwani           196057           169531                  Haryana
242       Ambala           195153           139279                  Haryana
255        Sirsa           182534           160735                  Haryana

In [88]:
df111=df11.drop('State or Union Territory', inplace=True, axis=1) 
df111

C:\Users\home\AppData\Local\Temp\ipykernel_18300\263679859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df111=df11.drop('State or Union Territory', inplace=True, axis=1)

In [89]:
Haryana=df11
Haryana

          Cities Population(2011) Population(2001)
25     Faridabad          1414050          1055938
56       Gurgaon           876824           173542
124       Rohtak           373133           286807
156      Panipat           294150           261740
162       Karnal           286974           210476
171      Sonipat           277053           214974
214  Yamunanagar           216677           189696
219    Panchkula           211355           140925
240      Bhiwani           196057           169531
242       Ambala           195153           139279
255        Sirsa           182534           160735

In [90]:
Haryana.index

Int64Index([25, 56, 124, 156, 162, 171, 214, 219, 240, 242, 255], dtype='int64')

In [91]:
len(Haryana.index)

11

In [92]:
mean_rank=(26+57+125+157+163+172+215+220+241+243+256)/11
Haryana_mean_rank=mean_rank
Haryana_mean_rank

170.45454545454547

In [93]:
df12=dfs1[dfs1['State or Union Territory']== 'Jharkhand' ]
display(dfs1[dfs1["State or Union Territory"]=='Jharkhand' ])

          Cities Population(2011) Population(2001) State or Union Territory
33       Dhanbad          1162472          1065327                Jharkhand
38        Ranchi          1073427           847093                Jharkhand
72    Jamshedpur           631364           573096                Jharkhand
112       Bokaro           413934           393805                Jharkhand
204        Mango           223805           166125                Jharkhand
228      Deoghar           203123           112525                Jharkhand
251       Phusro           186139            83463                Jharkhand
280   Hazaribagh           153599           127243                Jharkhand
286      Giridih           143529          unknown                Jharkhand
295      Ramgarh           132441            73455                Jharkhand
301  Medininagar           120325          unknown                Jharkhand

In [94]:
df121=df12.drop('State or Union Territory', inplace=True, axis=1) 
df121

C:\Users\home\AppData\Local\Temp\ipykernel_18300\1183516623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df121=df12.drop('State or Union Territory', inplace=True, axis=1)

In [95]:
Jharkhand=df12
Jharkhand

          Cities Population(2011) Population(2001)
33       Dhanbad          1162472          1065327
38        Ranchi          1073427           847093
72    Jamshedpur           631364           573096
112       Bokaro           413934           393805
204        Mango           223805           166125
228      Deoghar           203123           112525
251       Phusro           186139            83463
280   Hazaribagh           153599           127243
286      Giridih           143529          unknown
295      Ramgarh           132441            73455
301  Medininagar           120325          unknown

In [96]:
Jharkhand.index

Int64Index([33, 38, 72, 112, 204, 228, 251, 280, 286, 295, 301], dtype='int64')

In [97]:
len(Jharkhand.index)

11

In [98]:
mean_rank=(34+39+73+113+205+229+252+281+287+296+302)/11
Jharkhand_mean_rank=mean_rank
Jharkhand_mean_rank

191.9090909090909

In [99]:
df13=dfs1[dfs1['State or Union Territory']== 'Telangana' ]
display(dfs1[dfs1["State or Union Territory"]=='Telangana' ])

,Cities,Population(2011),Population(2001),State or Union Territory
4,Hyderabad,6809970,3637483,Telangana
61,Warangal[11][12],830281,530636,Telangana
150,Nizamabad,310467,288722,Telangana
153,Khammam,305000,218689,Telangana
179,Karimnagar,260899,205653,Telangana
196,Ramagundam[24],229644,236600,Telangana
212,Secunderabad,217910,206102,Telangana
276,Mahbubnagar,158000,unknown,Telangana
307,Suryapet,115250,94585,Telangana
308,Miryalaguda,109891,91395,Telangana

In [100]:

df131=df13.drop('State or Union Territory', inplace=True, axis=1) 
df131

C:\Users\home\AppData\Local\Temp\ipykernel_18300\926456067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df131=df13.drop('State or Union Territory', inplace=True, axis=1)

In [101]:
Telangana=df13
Telangana

               Cities Population(2011) Population(2001)
4           Hyderabad          6809970          3637483
61   Warangal[11][12]           830281           530636
150         Nizamabad           310467           288722
153           Khammam           305000           218689
179        Karimnagar           260899           205653
196    Ramagundam[24]           229644           236600
212      Secunderabad           217910           206102
276       Mahbubnagar           158000          unknown
307          Suryapet           115250            94585
308       Miryalaguda           109891            91395

In [102]:
Telangana.index

Int64Index([4, 61, 150, 153, 179, 196, 212, 276, 307, 308], dtype='int64')

In [103]:
len(Telangana.index)

10

In [104]:
mean_rank=(5+62+151+154+180+197+213+277+308+309)/10
Telangana_mean_rank=mean_rank
Telangana_mean_rank

185.6

In [105]:
df14=dfs1[dfs1['State or Union Territory']== 'Assam' ]
display(dfs1[dfs1["State or Union Territory"]=='Assam' ])

         Cities Population(2011) Population(2001) State or Union Territory
48     Guwahati           957352           809895                    Assam
197     Silchar           229136           184105                    Assam
278   Dibrugarh           154296           137661                    Assam
279      Jorhat           153889           112026                    Assam
283      Nagaon           148496           123265                    Assam
290  Bongaigaon           139650           101213                    Assam
296    Tinsukia           126389           101957                    Assam
320      Tezpur           102505            83028                    Assam

In [106]:
df141=df14.drop('State or Union Territory', inplace=True, axis=1) 
df141

C:\Users\home\AppData\Local\Temp\ipykernel_18300\263351143.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df141=df14.drop('State or Union Territory', inplace=True, axis=1)

In [107]:
Assam=df14
Assam

         Cities Population(2011) Population(2001)
48     Guwahati           957352           809895
197     Silchar           229136           184105
278   Dibrugarh           154296           137661
279      Jorhat           153889           112026
283      Nagaon           148496           123265
290  Bongaigaon           139650           101213
296    Tinsukia           126389           101957
320      Tezpur           102505            83028

In [108]:
Assam.index

Int64Index([48, 197, 278, 279, 283, 290, 296, 320], dtype='int64')

In [109]:
len(Assam.index)

8

In [110]:
mean_rank=(49+198+279+280+284+291+297+321)/8
Assam_mean_rank=mean_rank
Assam_mean_rank

249.875

In [111]:
df15=dfs1[dfs1['State or Union Territory']== 'Delhi' ]
display(dfs1[dfs1["State or Union Territory"]=='Delhi' ])

,Cities,Population(2011),Population(2001),State or Union Territory
2,Delhi,11007835,9879172,Delhi
167,Kirari Suleman Nagar,282598,153874,Delhi
185,New Delhi,249998,302147,Delhi
203,Karawal Nagar,224666,148549,Delhi
225,Nangloi Jat,205596,150948,Delhi
238,Bhalswa Jahangir Pur,197148,152339,Delhi
258,Sultan Pur Majra,181554,164426,Delhi

In [112]:
df151=df15.drop('State or Union Territory', inplace=True, axis=1) 
df151

C:\Users\home\AppData\Local\Temp\ipykernel_18300\1944905312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df151=df15.drop('State or Union Territory', inplace=True, axis=1)

In [113]:
Delhi=df15
Delhi

                   Cities Population(2011) Population(2001)
2                   Delhi         11007835          9879172
167  Kirari Suleman Nagar           282598           153874
185             New Delhi           249998           302147
203         Karawal Nagar           224666           148549
225           Nangloi Jat           205596           150948
238  Bhalswa Jahangir Pur           197148           152339
258      Sultan Pur Majra           181554           164426

In [114]:
Delhi.index

Int64Index([2, 167, 185, 203, 225, 238, 258], dtype='int64')

In [115]:
len(Delhi.index)

7

In [116]:
mean_rank=(3+168+186+204+226+239+259)/7
Delhi_mean_rank=mean_rank
Delhi_mean_rank

183.57142857142858

In [117]:
df16=dfs1[dfs1['State or Union Territory']== 'Kerala' ]
display(dfs1[dfs1["State or Union Territory"]=='Kerala' ])

,Cities,Population(2011),Population(2001),State or Union Territory
65,Thiruvananthapuram,752490,368618,Kerala
76,Kochi,601574,596473,Kerala
109,Kozhikode,432097,436556,Kerala
132,Kollam,349033,361560,Kerala
146,Thrissur,315596,317526,Kerala
266,Alappuzha,174164,177029,Kerala
267,Kottayam,172878,129894,Kerala

In [118]:
df161=df16.drop('State or Union Territory', inplace=True, axis=1) 
df161

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2441173169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df161=df16.drop('State or Union Territory', inplace=True, axis=1)

In [119]:
Kerala=df16
Kerala

                 Cities Population(2011) Population(2001)
65   Thiruvananthapuram           752490           368618
76                Kochi           601574           596473
109           Kozhikode           432097           436556
132              Kollam           349033           361560
146            Thrissur           315596           317526
266           Alappuzha           174164           177029
267            Kottayam           172878           129894

In [120]:
Kerala.index

Int64Index([65, 76, 109, 132, 146, 266, 267], dtype='int64')

In [121]:
len(Kerala.index)

7

In [122]:
mean_rank=(69+80+113+136+150+270+271)/7
Kerala_mean_rank=mean_rank
Kerala_mean_rank

155.57142857142858

In [123]:
df17=dfs1[dfs1['State or Union Territory']== 'Punjab' ]
display(dfs1[dfs1["State or Union Territory"]=='Punjab' ])

        Cities Population(2011) Population(2001) State or Union Territory
22    Ludhiana          1618879          1398467                   Punjab
34    Amritsar          1132383           966862                   Punjab
58   Jalandhar           862196           706043                   Punjab
115    Patiala           405164           303151                   Punjab
163   Bathinda           285813           217256                   Punjab
303   Phagwara           117966          unknown                   Punjab

In [124]:
df171=df17.drop('State or Union Territory', inplace=True, axis=1) 
df171

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2044003650.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df171=df17.drop('State or Union Territory', inplace=True, axis=1)

In [125]:
Punjab=df17
Punjab

        Cities Population(2011) Population(2001)
22    Ludhiana          1618879          1398467
34    Amritsar          1132383           966862
58   Jalandhar           862196           706043
115    Patiala           405164           303151
163   Bathinda           285813           217256
303   Phagwara           117966          unknown

In [126]:
Punjab.index

Int64Index([22, 34, 58, 115, 163, 303], dtype='int64')

In [127]:
len(Punjab.index)

6

In [128]:
mean_rank=(26+38+62+119+167+307)/6
Punjab_mean_rank=mean_rank
Punjab_mean_rank

119.83333333333333

In [129]:
df18=dfs1[dfs1['State or Union Territory']== 'Chhattisgarh' ]
display(dfs1[dfs1["State or Union Territory"]=='Chhattisgarh'])

       Cities Population(2011) Population(2001) State or Union Territory
45     Raipur          1010087           605747             Chhattisgarh
73     Bhilai           625697           556366             Chhattisgarh
126     Korba           363210           315690             Chhattisgarh
137  Bilaspur           335761           296662             Chhattisgarh
173      Durg           268679           232517             Chhattisgarh
282   Raigarh           150019           115908             Chhattisgarh

In [130]:
df181=df18.drop('State or Union Territory', inplace=True, axis=1) 
df181

C:\Users\home\AppData\Local\Temp\ipykernel_18300\879058023.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df181=df18.drop('State or Union Territory', inplace=True, axis=1)

In [131]:
Chhattisgarh=df18
Chhattisgarh

       Cities Population(2011) Population(2001)
45     Raipur          1010087           605747
73     Bhilai           625697           556366
126     Korba           363210           315690
137  Bilaspur           335761           296662
173      Durg           268679           232517
282   Raigarh           150019           115908

In [132]:
len(Chhattisgarh.index)

6

In [133]:
mean_rank=(49+77+130+141+177+286)/6
Chhattisgarh_mean_rank=mean_rank
Chhattisgarh_mean_rank

143.33333333333334

In [134]:
df19=dfs1[dfs1['State or Union Territory']== 'Odisha' ]
display(dfs1[dfs1["State or Union Territory"]=='Odisha'])

          Cities Population(2011) Population(2001) State or Union Territory
59   Bhubaneswar           837737           648032                   Odisha
74       Cuttack           606007           534654                   Odisha
82      Rourkela           552734           426354                   Odisha
128    Berhampur           355823           307792                   Odisha
138    Sambalpur           330106           274917                   Odisha
230         Puri           201026           152682                   Odisha

In [135]:
df191=df19.drop('State or Union Territory', inplace=True, axis=1) 
df191

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2722909456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df191=df19.drop('State or Union Territory', inplace=True, axis=1)

In [136]:
Odisha=df19
df19

          Cities Population(2011) Population(2001)
59   Bhubaneswar           837737           648032
74       Cuttack           606007           534654
82      Rourkela           552734           426354
128    Berhampur           355823           307792
138    Sambalpur           330106           274917
230         Puri           201026           152682

In [137]:
len(Odisha.index)

6

In [138]:
Odisha.index

Int64Index([59, 74, 82, 128, 138, 230], dtype='int64')

In [139]:
mean_rank=(63+78+86+132+142+234)/6
Odisha_mean_rank=mean_rank
Odisha_mean_rank

122.5

In [140]:
 df20=dfs1[dfs1['State or Union Territory']== 'Jammu and Kashmir' ]
display(dfs1[dfs1["State or Union Territory"]=='Jammu and Kashmir'])

        Cities Population(2011) Population(2001) State or Union Territory
31    Srinagar          1180570           898440        Jammu and Kashmir
94   Jammu[16]           503690           369959        Jammu and Kashmir
309   Anantnag           108505          unknown        Jammu and Kashmir

In [141]:
df201=df20.drop('State or Union Territory', inplace=True, axis=1) 
df201

C:\Users\home\AppData\Local\Temp\ipykernel_18300\4170251745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df201=df20.drop('State or Union Territory', inplace=True, axis=1)

In [142]:
Jammu_Kashmir=df20
Jammu_Kashmir

        Cities Population(2011) Population(2001)
31    Srinagar          1180570           898440
94   Jammu[16]           503690           369959
309   Anantnag           108505          unknown

In [143]:
Jammu_Kashmir.index

Int64Index([31, 94, 309], dtype='int64')

In [144]:
mean_rank=(35+98+313)/3
Jammu_Kashmir_mean_rank=mean_rank
Jammu_Kashmir_mean_rank

148.66666666666666

In [145]:


 df21=dfs1[dfs1['State or Union Territory']== 'Puducherry' ]
display(dfs1[dfs1["State or Union Territory"]=='Puducherry'])

           Cities Population(2011) Population(2001) State or Union Territory
154  Uzhavarkarai           300028           217707               Puducherry
189   Pondicherry           241773           220749               Puducherry

In [146]:
df211=df21.drop('State or Union Territory', inplace=True, axis=1) 
df211

C:\Users\home\AppData\Local\Temp\ipykernel_18300\1538646386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df211=df21.drop('State or Union Territory', inplace=True, axis=1)

In [147]:
Puducherry=df21
Puducherry

           Cities Population(2011) Population(2001)
154  Uzhavarkarai           300028           217707
189   Pondicherry           241773           220749

In [148]:
Puducherry.index

Int64Index([154, 189], dtype='int64')

In [149]:
mean_rank=(154+189)/2
Puducherry_mean_rank=mean_rank
Puducherry_mean_rank

171.5

In [150]:
 df22=dfs1[dfs1['State or Union Territory']== 'Uttarakhand' ]
display(dfs1[dfs1["State or Union Territory"]=='Uttarakhand'])

       Cities Population(2011) Population(2001) State or Union Territory
79   Dehradun           578420           426674              Uttarakhand
198  Haridwar           228832           175010              Uttarakhand

In [151]:
df221=df22.drop('State or Union Territory', inplace=True, axis=1) 
df221

C:\Users\home\AppData\Local\Temp\ipykernel_18300\3934221283.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df221=df22.drop('State or Union Territory', inplace=True, axis=1)

In [152]:
Uttarakhand=df22
df22

       Cities Population(2011) Population(2001)
79   Dehradun           578420           426674
198  Haridwar           228832           175010

In [153]:
Uttarakhand.index

Int64Index([79, 198], dtype='int64')

In [154]:
mean_rank=(79+198)/2
Uttarakhand_mean_rank=mean_rank
Uttarakhand_mean_rank

138.5

In [155]:
ser= pd.value_counts(dfs1['State or Union Territory'])
ser1= ser[ser==1]
ser1

Tripura                           1
Chandigarh                        1
Mizoram                           1
Manipur                           1
Himachal Pradesh                  1
Andaman and Nicobar Islands UT    1
Sikkim                            1
Goa                               1
Name: State or Union Territory, dtype: int64

In [156]:
df23=dfs1.iloc[[46,116,158,173,268,287,322,323],:]
df23

,Cities,Population(2011),Population(2001),State or Union Territory
47,Chandigarh,960787,808515,Chandigarh
117,Agartala,399688,271811,Tripura
159,Aizawl,291822,228280,Mizoram
174,Imphal,264986,221492,Manipur
269,Shimla,169578,142555,Himachal Pradesh
288,Port Blair,140572,unknown,Andaman and Nicobar Islands UT
323,Gangtok,100286,29354,Sikkim
324,Vasco Da Gama,100000,unknown,Goa

In [157]:
df23.index

Int64Index([47, 117, 159, 174, 269, 288, 323, 324], dtype='int64')

In [158]:
len(df23.index)

8

In [159]:
#To select rows whose column value equals a scalar, some_value, use ==:
#dfs1.loc[dfs1['State or Union Territory'] == 'Tripura'and"Chandigarh"]

In [160]:
# df[df['price'] < 20000]
# df[(df['price'] < 30000) & (df['mileage'] < 2000)]

In [161]:
mean_rank=(47+117+159+269+288+323+324)/7

Single_City_mean_rank=mean_rank
Single_City_mean_rank

218.14285714285714

In [162]:
ping={'State or Union Territory':["Uttar_Pradesh ","Maharashtra ","Andhra_Pradesh","West_Bengal","Bihar","Tamil_Nadu","Madhya Pradesh","Karnataka ","Gujarat","Rajasthan","Haryana","Jharkhand","Telangana","Assam","Delhi","Kerala ","Punjab","Chhattisgarh","Odisha ","Jammu and Kashmir","Puducherry","Uttarakhand","Tripura","Chandigarh ","Mizoram ","Manipur","Himachal Pradesh","Andaman and Nicobar Islands UT","Sikkim ","Goa "]}


df65 = pd.DataFrame(ping)
df65.index +=1
df65.index
df65

          State or Union Territory
1                   Uttar_Pradesh
2                     Maharashtra
3                   Andhra_Pradesh
4                      West_Bengal
5                            Bihar
6                       Tamil_Nadu
7                   Madhya Pradesh
8                       Karnataka
9                          Gujarat
10                       Rajasthan
11                         Haryana
12                       Jharkhand
13                       Telangana
14                           Assam
15                           Delhi
16                         Kerala
17                          Punjab
18                    Chhattisgarh
19                         Odisha
20               Jammu and Kashmir
21                      Puducherry
22                     Uttarakhand
23                         Tripura
24                     Chandigarh
25                        Mizoram
26                         Manipur
27                Himachal Pradesh
28  Andaman and Nicobar Islands UT
29                         Sikkim
30                            Goa

In [167]:
df65.insert(0,"Mean_Rank", [140.7027027027027, 90.09375, 214.90322580645162,165.066666666666666,140.08,159.181818181812,161.05555555555554,142.14375,142.85714285714286,117.83333333333333,170.45454545454547,191.9090909090909,185.6,249.875,183.57142857142858,155.57142857142858,119.83333333333333,143.33333333333334,122.5,148.66666666666666,171.5,138.5,117,47,159,174,269,288,323,324], True)
df65

     Mean_Rank   Mean_Rank   Mean_Rank        State or Union Territory
1   140.702703  140.702703  140.702703                  Uttar_Pradesh
2    90.093750   90.093750   90.093750                    Maharashtra
3   214.903226  214.903226  214.903226                  Andhra_Pradesh
4   165.066667  165.066667  165.066667                     West_Bengal
5   140.080000  140.080000  140.080000                           Bihar
6   159.181818  159.181818  159.181818                      Tamil_Nadu
7   161.055556  161.055556  161.055556                  Madhya Pradesh
8   142.143750  142.143750  142.143750                      Karnataka
9   142.857143  142.857143  142.857143                         Gujarat
10  117.833333  117.833333  117.833333                       Rajasthan
11  170.454545  170.454545  170.454545                         Haryana
12  191.909091  191.909091  191.909091                       Jharkhand
13  185.600000  185.600000  185.600000                       Telangana
14  249.875000  249.875000  249.875000                           Assam
15  183.571429  183.571429  183.571429                           Delhi
16  155.571429  155.571429  155.571429                         Kerala
17  119.833333  119.833333  119.833333                          Punjab
18  143.333333  143.333333  143.333333                    Chhattisgarh
19  122.500000  122.500000  122.500000                         Odisha
20  148.666667  148.666667  148.666667               Jammu and Kashmir
21  171.500000  171.500000  171.500000                      Puducherry
22  138.500000  138.500000  138.500000                     Uttarakhand
23  117.000000  117.000000  117.000000                         Tripura
24   47.000000   47.000000   47.000000                     Chandigarh
25  159.000000  159.000000  159.000000                        Mizoram
26  174.000000  174.000000  174.000000                         Manipur
27  269.000000  269.000000  269.000000                Himachal Pradesh
28  288.000000  288.000000  288.000000  Andaman and Nicobar Islands UT
29  323.000000  323.000000  323.000000                         Sikkim
30  324.000000  324.000000  324.000000                            Goa

In [164]:
df65.mean(axis = 0)

C:\Users\home\AppData\Local\Temp\ipykernel_18300\2771550293.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df65.mean(axis = 0)

Mean_Rank    171.874426
dtype: float64

### Average of mean rank(171.874426)  of top 250 cities of india  is equal to Puducherry(171.500000)

In [165]:
Uttar Pradesh                   
Maharashtra                  
Andhra Pradesh                    
West Bengal                      
Bihar                             
Tamil Nadu                       
Madhya Pradesh                    
Karnataka                         
Gujarat                          
Rajasthan                        
Haryana                          
Jharkhand                        
Telangana                         
Assam                              
Delhi                              
Kerala                             
Punjab                             
Chhattisgarh                       
Odisha                             
Jammu and Kashmir                  
Puducherry                         
Uttarakhand                        
Tripura                         
Chandigarh                         
Mizoram                           
Manipur                           
Himachal Pradesh                  
Andaman and Nicobar Islands UT    

Sikkim                             
Goa

SyntaxError: invalid syntax (722225896.py, line 1)

In [ ]:
df111=pd.DataFrame({"Mean Rank":[140.7027027027027, 90.09375, 214.90322580645162, 165.06666666666666,140.08,159.1818181818182,161.05555555555554,142.4375.142.85714285714286,117.83333333333333,170.45454545454547,191.9090909090909,185.6,249.875,183.57142857142858,155.57142857142858,119.83333333333333,143.33333333333334,122.5,148.66666666666666,171.5,138.5,117,47,159,174,269,288,323,324],
                'State or Union Territory':["Uttar_Pradesh ","Maharashtra ","Andhra_Pradesh","West_Bengal","Bihar","Tamil_Nadu","Madhya Pradesh","Karnataka ","Gujarat","Rajasthan","Haryana","Jharkhand","Telangana","Assam","Delhi","Kerala ","Punjab","Chhattisgarh","Odisha ","Jammu and Kashmir","Puducherry","Uttarakhand","Tripura","Chandigarh ","Mizoram ","Manipur","Himachal Pradesh","Andaman and Nicobar Islands UT","Sikkim ","Goa "],
})

In [ ]:
mean_rank=pd.Series(['140.7027027027027', '90.09375', '214.90322580645162', '165.06666666666666',"140.08","159.1818181818182","161.05555555555554","142.4375"."142.85714285714286","117.83333333333333","170.45454545454547","191.9090909090909","185.6","249.875","183.57142857142858","155.57142857142858","119.83333333333333","143.33333333333334","122.5","148.66666666666666","171.5","138.5","117","47","159","174","269","288","323","324"],index=[0,1,2])

In [ ]:
Mean_rank=pd.Series([140.7027027027027, 90.09375, 214.90322580645162, 165.06666666666666,140.08,159.1818181818182,161.05555555555554,142.4375.142.85714285714286,117.83333333333333,170.45454545454547,191.9090909090909,185.6,249.875,183.57142857142858,155.57142857142858,119.83333333333333,143.33333333333334,122.5,148.66666666666666,171.5,138.5,117,47,159,174,269,288,323,324],index=[0,1,2])